### ISSUE TITLE
编译报错 antd/lib/style/index.css:10   Unexpected token

### ISSUE THREAD

**Issue by forrest23** [ant-design/babel-plugin-import#100]
我用 https://github.com/kriasoft/react-starter-kit 这个脚手架，现在想用antd, 按照说明安装了babel-plugin-import，然后在webpack.config 文件里面增加了['import', { libraryName: 'antd', style: 'css' }],

 loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, '../src'),
        ],
        query: {
          // https://github.com/babel/babel-loader#options
          cacheDirectory: isDebug,

          // https://babeljs.io/docs/usage/options/
          babelrc: false,
          presets: [
            // Latest stable ECMAScript features
            // https://github.com/babel/babel/tree/master/packages/babel-preset-latest
            'latest',
            // Experimental ECMAScript proposals
            // https://github.com/babel/babel/tree/master/packages/babel-preset-stage-0
            'stage-0',
            // JSX, Flow
            // https://github.com/babel/babel/tree/master/packages/babel-preset-react
            'react',
            ...isDebug ? [] : [
              // Optimize React code for the production build
              // https://github.com/thejameskyle/babel-react-optimize
              'react-optimize',
            ],
          ],
          plugins: [
            // Externalise references to helpers and builtins,
            // automatically polyfilling your code without polluting globals.
            // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime
            'transform-runtime',
            ...!isDebug ? [] : [
              // Adds component stack to warning messages
              // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source
              'transform-react-jsx-source',
              // Adds __self attribute to JSX which React will use for some warnings
              // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-self
              'transform-react-jsx-self',
            ],
            **['import', { libraryName: 'antd', style: 'css' }],**
          ],
        },
      },
      {
        test: /\.css/,
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            // CSS Loader https://github.com/webpack/css-loader
            importLoaders: 1,
            sourceMap: isDebug,
            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]',
            // CSS Nano http://cssnano.co/options/
            minimize: !isDebug,
            discardComments: { removeAll: true },
          })}`,
          'postcss-loader?pack=default',
        ],
      },
      {
        test: /\.less$/,
        loader: 'style!css!less',
        include: path.resolve(__dirname, 'node_modules'),
      },
      {
        test: /\.json$/,
        loader: 'json-loader',
      },
      {
        test: /\.txt$/,
        loader: 'raw-loader',
      },
      {
        test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
        loader: 'file-loader',
        query: {
          name: isDebug ? '[path][name].[ext]?[hash:8]' : '[hash:8].[ext]',
        },
      },
      {
        test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          name: isDebug ? '[path][name].[ext]?[hash:8]' : '[hash:8].[ext]',
          limit: 10000,
        },
      },
    ],

编译报错：
Users/fgmh/Project/React/ReactWeb/node_modules/antd/lib/style/index.css:10
html {
     ^
SyntaxError: Unexpected token {

**Comment by YingQQQ** [comment]
我也遇到了~

**Comment by sorrycc** [comment]
node_modules 下的 css 文件没解析吧，推荐用 [roadhog](https://github.com/sorrycc/roadhog) 作为工具，没这么乱七八糟的问题。

**Comment by MinJieLiu** [comment]
我也遇到这个问题了 @YingQQQ @forrest23 你们有没有解决这个问题呢，这个问题关得太草率了

**Comment by yixiaoxi** [comment]
同样遇到该问题，看来是没办法解决了？

**Comment by MinJieLiu** [comment]
@yixiaoxi 那个starter-kit 目前我也只是只能全局导入 css

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/96

**Comment by vonxq** [comment]
我解决了，加了webpack的rules中添加css-loader，加include字段会报一样的错，不知道有没有人知道为什么
```
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
          include: [path.join(__dirname, 'src'), path.join(__dirname, 'node-modules/antd')](删掉这一行就好了)
        }
```

**Comment by Shawson** [comment]
While I can't read the comments here, the code sample saved me- I also wasn't including the node_modules/antd folder

**Comment by justQing00** [comment]
当为服务器的时候，不进行处理即可
[https://github.com/zeit/next-plugins/issues/70](https://github.com/zeit/next-plugins/issues/70)

**Comment by eminoda** [comment]
或许各位漏掉了这样的代码？因为 antd-mobile/style 内只有 css or less，所以要添加对应的 loader parser

```javascript
      {
        test: /\.css$/i,
        use: ['style-loader','css-loader']
      },
```
