### ISSUE TITLE
使用了babel-plugin-import，仍旧看到提示prebuilt信息

### ISSUE THREAD

**Issue by slashhuang** [ant-design/babel-plugin-import#110]
babelrc如下
`{
    "presets": [
        "es2015",
        "react",
        "stage-0"
    ],
    "plugins": [
        ["import",{
          "libraryName": "antd",
          "style": true
        }],
        "transform-decorators-legacy",
    	"add-module-exports",
        "transform-object-assign",
		"transform-es3-property-literals",
		"transform-es3-member-expression-literals"
    ]
}`
仍旧看到这个信息
You are using prebuilt antd,
please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

**Comment by sorrycc** [comment]
手动引了 antd 的样式了?

**Comment by Restry** [comment]
对，我就是有手动引用样式问题。改变颜色

**Comment by Restry** [comment]
`{
  "presets": [
    "react",
    "es2015",
    "stage-1"
  ],
  "plugins": [
    "transform-runtime",

      [
        "import",
        {
          "libraryName": "antd",
          "style": "css" // or 'css'
        }
      ]

  ]
}
`

不引用样式了也一样有提示。我没搞明白这个插件的意义，用了后就能自己按需要加载了？ 没有引用到的antd 组件就不自己加载是吗？  我在用了插件后webpack打包反而还变大了

**Comment by Alex1990** [comment]
在这里记录下我是如何遇到类似问题的。我自己基于 antd （配置成`"devDependencies"`）写了一个 UI 组件，然后将组件编译成了 ES5 代码，默认 npm package.json 里面的`"main"`字段指向这个 ES5 代码，显然 babel-plugin-import 不会处理 ES5 的代码，于是 webpack 打包的时候就把 antd/dist/antd.js 打包了。

**Comment by paranoidjk** [comment]
https://github.com/ant-design/babel-plugin-import#example
https://github.com/ant-design/ant-design-mobile/wiki/How-babel-plugin-import-load-stysheet%3F
