### ISSUE TITLE
如何与ts-loader同时使用？

### ISSUE THREAD

**Issue by MrKou47** [ant-design/babel-plugin-import#113]
组件都是`tsx`格式的，怎样将babel-loader 与ts-loader同时使用？并且我的按需加载也无效，
.babelrc
```js
{
    "presets": ["es2015", "stage-0", "react"],
    "plugins": [
        ["import", {
            "libraryName": "antd",
            "style": "css"
        }]
    ]
}
```

```js
/* build/webpack.config.js */
const webpack = require('webpack');
const path = require('path');
const publicPath = 'http://localhost:8000/statics/js';


const config = {
    entry: './app/client.tsx',
    output: {
        filename: 'bundle.js',
        path: path.join(__dirname, '/dist/'),
        publicPath: publicPath
    },
    devtool: 'source-map',
    resolve: {
        extensions: ['.web.js', '.ts', '.tsx', '.js']
    },
    module: {
        loaders: [{
                test: /\.tsx?$/,
                loader: ['babel-loader','ts-loader'],
            },
            {
                test: /\.css$/,
                loader: ['style-loader', 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]']
            },
            { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' }
        ]
    },
    devtool: 'eval',
}

module.exports = config;
```

这样打包出来的js不仅很大，而且样式也没有加载出来，怎么回事？

**Comment by BirdLeeSCUT** [comment]
我用webpack2 + awesome-typescript-loader , 也加了 babel-loader  在前面，同样也是没有办法按需加载

**Comment by BirdLeeSCUT** [comment]
希望能够给出 typescript 的解决方案。
不过如果 awesome-typescript-loader 或 typescript-loader 支持 webpack 2 的 tree shaking 特性，那么不用这个插件，按需加载的功能会自动实现了 ？

**Comment by whyming** [comment]
我也是webpack2 + awesome-typescript-loader，css需要手动加载，打包的文件也很大，没有按需加载，官方组件是typescript写的，现在对typescript使用者不太友好

**Comment by afc163** [comment]
https://segmentfault.com/q/1010000008082763

**Comment by BirdLeeSCUT** [comment]
用上面链接的方法，我在webpack2 + awesome-typescript-loader 好会出现 declare global ，namespace 无法识别的问题，大家有谁成功了可以截一下配置文件的图吗？ （webpack2 + awesome-typescript-loader）

**Comment by johnbian** [comment]
@BirdLeeSCUT 成功了嘛？可以做到按需加载了吗。。我的环境和你一样的

**Comment by bylevel** [comment]
我这边能成功的按需加载，主要有下面几点你们可以参考一下:

代码里面的引用方式使用下面这种

```js
import { Button } from 'antd';
```

tsconfig.json

```json
{
  "compilerOptions": {
    "outDir": "build",
    "target": "es6",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "types": [
    "typePatches"
  ]
}
```

`"target": "es6"` 是为了将ts输出成es6再交给babel处理
`"jsx": "preserve"` 是为了保持 jsx 格式输出，由 babel 做 jsx 转换，这个直接写成 react 由 ts 转也没什么问题。

.babelrc

```json
{
    "presets": ["es2015", "react", "stage-0"],
    "plugins": [
        "add-module-exports",
        "transform-runtime", [
            "import", [
                {
                    "style": "css",
                    "libraryName": "antd"
                }
            ]
        ]
    ]
}
```

webpack.config.js 里面则是要注意把ts的输出交给babel

```js
      {
        test: /\.(ts|tsx)$/,
        include: paths.appSrc,
        loader: 'babel!ts',
      },
```

**Comment by chj-damon** [comment]
终于找到正确的方式了。谢谢 @bylevel

**Comment by Brooooooklyn** [comment]
写了一个 ts import plugin，可以不经过 babel, 直接用  ts 编译
大家有兴趣可以试一下:
https://github.com/Brooooooklyn/ts-import-plugin

**Comment by DavidNorena** [comment]
Guys I love your language and would love to understand you, but can you please guys tell me how did you solve it ... Im using awesome-typescript-loader ts-import-plugin is not working for me :( @Brooooooklyn

**Comment by Brooooooklyn** [comment]
@DavidNorena Could you please open issue in https://github.com/Brooooooklyn/ts-import-plugin , and give me more detail about your configuration?

**Comment by DavidNorena** [comment]
@Brooooooklyn sure man Thank you so much !

**Comment by qlqllu** [comment]
Here is my config that works:

* tsconfig.json
```
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "target": "es6",
    "jsx": "preserve",
    "moduleResolution": "node", 
    "allowSyntheticDefaultImports": true
  },
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "useCache": false,
    "emitRequireType": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

* webpack.config.js
```
{
        test: /\.tsx?$/,
        loader: 'awesome-typescript-loader',
        exclude: /node_modules/,
        options: {
          babelOptions: {
            "presets": ["react"],
            "plugins": [
              ["import", { "libraryName": "antd", "style": true }]
            ]
          }
        }
      }

{
        test: /\.less$/,
        use: [
          'style-loader', 
        {
          loader: 'css-loader',
          options: {
            localIdentName: '[name]__[local]',
            sourceMap: true
          }
        }, {
          loader: 'less-loader',
          options: {
            modifyVars: antdTheme
          }
        }]
      }
```

**Comment by gwuhaolin** [comment]
[ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 可以做到。

它是一个 babel-plugin-import 的代替品，一个 Webpack Loader，优势有：
- 性能更好；
- 能用于非 Babel 的项目，只要你的项目使用 Webpack 构建即可；

**Comment by DavidNorena** [comment]
@gwuhaolin can you please explain it in english ? also is it compatible with awesome-typescript-loader

**Comment by gwuhaolin** [comment]
@DavidNorena 
# ui-component-loader
Modular UI component loader for webpack, a good alternative for [babel-plugin-import](https://github.com/ant-design/babel-plugin-import).

Compatible with [antd](https://github.com/ant-design/ant-design), [antd-mobile](https://github.com/ant-design/ant-design-mobile), and so on.

### Example

| description | options | source | output |
| --- | --- | --- | --- |
| replace one | `lib: 'antd'` | `import {Button} from 'antd'` | `import Button from 'antd/lib/Button'` |
| replace many | `lib: 'antd'` | `import {Button,Icon} from 'antd'` | `import Button from 'antd/lib/Button' import Icon from 'antd/lib/Icon'` |
| set libDir | `lib: 'antd', libDir: 'es'` | `import {Button} from 'antd'` | `import Button from 'antd/es/Button'` |
| use style | `lib: 'antd', style: 'index.css'` | `import {Button} from 'antd'` | `import Button from 'antd/lib/Button' import 'antd/lib/Button/index.css'` |
| translate camel | `lib: 'antd', camel2: '-'` | `import {MyComponent} from 'antd'` | `import MyComponent from 'antd/lib/my-component'` |

  
### Usage
Install by:
```bash
npm install ui-component-loader -D
```

Edit `webpack.config.js`:
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: [
          'ts-loader',
          {
            loader: 'ui-component-loader',
            options: {
              'lib': 'antd',
              'style': 'style/index.css',
            }
          },
        ],
        include: path.resolve(__dirname, 'node_modules/antd')
      },
    ]
  },
};
```
> The order of loaders has no require, but the source code pass to ui-component-loader must use ES6 module syntax.

## Options
- **lib**: library want to replace,value is name in npm.
- **libDir**: library directory path which store will use code, default it `lib`  
- **style**: should append style file to a component? value is relative path to style file.
- **camel2**: should translate MyComponent to my-component, value is the join string. 

## Diff with babel-plugin-import
1. babel-plugin-import is a babel plugin, which means must be used in project with babel.
But in some project, like project use TypeScript, ui-component-loader is useful,
ui-component-loader **can be used in any project with webpack**.
2. ui-component-loader **has better performance** as it's implement by regular expression replace string, but babel-plugin-import base on AST.

**Comment by chenkang084** [comment]
> Here is my config that works:
> 
> * tsconfig.json
> 
> ```
> {
>   "compileOnSave": false,
>   "buildOnSave": false,
>   "compilerOptions": {
>     "target": "es6",
>     "jsx": "preserve",
>     "moduleResolution": "node", 
>     "allowSyntheticDefaultImports": true
>   },
>   "awesomeTypescriptLoaderOptions": {
>     "useBabel": true,
>     "useCache": false,
>     "emitRequireType": false
>   },
>   "exclude": [
>     "node_modules"
>   ]
> }
> ```
> 
> * webpack.config.js
> 
> ```
> {
>         test: /\.tsx?$/,
>         loader: 'awesome-typescript-loader',
>         exclude: /node_modules/,
>         options: {
>           babelOptions: {
>             "presets": ["react"],
>             "plugins": [
>               ["import", { "libraryName": "antd", "style": true }]
>             ]
>           }
>         }
>       }
> 
> {
>         test: /\.less$/,
>         use: [
>           'style-loader', 
>         {
>           loader: 'css-loader',
>           options: {
>             localIdentName: '[name]__[local]',
>             sourceMap: true
>           }
>         }, {
>           loader: 'less-loader',
>           options: {
>             modifyVars: antdTheme
>           }
>         }]
>       }
> ```

it is very helpful . it works well using your recommendation
