### ISSUE TITLE
Add suffix option

### ISSUE THREAD

**Issue by cncolder** [ant-design/babel-plugin-import#116]
If you add a `suffix` option like this. Maybe this can save time for antd-mobile users

```json
{
    "libraryName": "antd-mobile",
    "suffix": "/index.web",
}
```

Then transform `import { Button } from 'antd-mobile'` to `var _button = require('antd-mobile/lib/button/index.web')`

**Comment by yesmeck** [comment]
@sorrycc 觉得如何，我也碰到需要能指定 `index` 文件的情况，可以的话我来个 PR。

**Comment by afc163** [comment]
use webpack resolve

**Comment by yesmeck** [comment]
antd-mobile 的测试 native 和 web 同时跑的话只能靠这个插件来处理。

**Comment by yesmeck** [comment]
@ @ 我在 https://github.com/ant-design/antd-demo-jest 里处理吧。

**Comment by cncolder** [comment]
这是我在尝试 antd-mobile 用于 SSR 过程中碰到的问题，当时的想法有点简单了，实际处理起来要更加复杂。光凭这个 PR 不足以解决问题。

要想真正解决 SSR 问题，服务端只能是 hacker require.extensions

**Comment by sorrycc** [comment]
@yesmeck 抱歉，这几个星期比较忙，刚看到。欢迎 PR。

**Comment by paranoidjk** [comment]
@yesmeck webpack resolve 应该可以解决这个问题？ native 和 web 同时跑可以起两个node，用两份webpack配置么？
