### ISSUE TITLE
Don't work with an update of meteor's package

### ISSUE THREAD

**Issue by Themandunord** [ant-design/babel-plugin-import#117]
Hi,

Since meteor update the package ecmascript to @0.6.3, this plugin don't work. (No import of the css and included the whole pacakge)
When I downgrade to ecmascipt @0.6.1, this plugin works again. (Import the css and only the good module)

So I don't know what to do. Who can help the comunity to fix this issue ?

**Comment by afc163** [comment]
Cause we don't use meteor, I affaid you should dig into this and help us to fix it.

**Comment by Themandunord** [comment]
Maybe the help can provided here : https://github.com/meteor/babel/issues/13 ?

**Comment by afc163** [comment]
It seems to be a meteor-babel bug?

**Comment by Themandunord** [comment]
Yes correct. 
https://github.com/meteor/meteor/issues/8399

The issue is open in the meteor github ;)

**Comment by zachguo** [comment]
they didn't fix this and [said](https://github.com/meteor/babel/issues/13#issuecomment-305236524):
> `babel-plugin-import` ... relies so heavily on quirks of the Babel plugin system, and in particular assumes that other plugins run later without doing anything to ensure that they run.
