### ISSUE TITLE
does it support sass?

### ISSUE THREAD

**Issue by gx761** [ant-design/babel-plugin-import#119]
my component's style is written in sass and named index.scss which placed in the component folder with index.jsx.

If i set the "style" configuration to true, will the sass file get included automatically? if not, which piece of code should i change to make it support sass?

**Comment by paranoidjk** [comment]
Yep, it should support sass.
But you may need to configure webpack loader and reolve.extension, i am not sure.

More detail please check:
doc: https://github.com/ant-design/babel-plugin-import#style
demo: https://github.com/ant-design/babel-plugin-import/tree/master/test/fixtures/import-css
