### ISSUE TITLE
分离到vendor的可能性？

### ISSUE THREAD

**Issue by Marshane** [ant-design/babel-plugin-import#124]
后续版本是否会实现这个功能，或有类似的方案？

**Comment by paranoidjk** [comment]
如 https://github.com/ant-design/babel-plugin-import/issues/133

build 产物并不是 babel-plugin-Import 所关注的，babel-plugin-Import 只是修改引用方式以实现按需加载。

分离 vender 请自行学习 webpack 配置。

**Comment by paranoidjk** [comment]
update, Readme 有写，不能与 vendor 结合使用 https://github.com/ant-design/babel-plugin-import#note
