### ISSUE TITLE
打包后不能与其他css文件合并成一个文件？

### ISSUE THREAD

**Issue by lovesong** [ant-design/babel-plugin-import#133]
如题，打包后，按需加载的antd的样式会独立打包成一个css文件，怎么和其他的文件合并呢？还是我只能用其他工具来做这个事？

**Comment by paranoidjk** [comment]
> 按需加载的antd的样式会独立打包成一个css文件

这件事情并不是 babel-plugin-import 做的，应该是你自己使用了 commonThunkPlugin 之类的配置，请自行检查。

**Comment by andriijas** [comment]
@sorrycc @paranoidjk whats the reason for not working well with vendor/commonchunks. is there any way we can fix this? would be nice to separate styles into vendor.css and all antd to vendor.js
