### ISSUE TITLE
集成 create-react-app 无效，样式丢失

### ISSUE THREAD

**Issue by pot-code** [ant-design/babel-plugin-import#139]
无论是在 webpack.config.dev 中的 loader 中配置，还是在 package.json 的 babel 部分配置都无效，仍然提示没有使用 import 插件，且样式丢失。

---

webpack 配置的代码
```
{
	test: /\.(js|jsx)$/,
	include: paths.appSrc,
	loader: 'babel',
	options: {
		plugins: [
			['import', { libraryName: 'antd', style: 'css' }]
		]
	},
	query: {
		cacheDirectory: true
	}
}
```

---

package.json 配置的代码
```
"babel": {
	"presets": [
		"react-app"
	],
	"plugins": [
		["import", {
			"libraryName": "antd",
			"style": "css"
		}]
	]
},
```

**Comment by afc163** [comment]
Cloud you provide a reproducible repo?

**Comment by pot-code** [comment]
@afc163 Latest create-react-app starter kit,  just eject it.

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by afc163** [comment]
Don't let me do this, you should provide a reproducible repo.

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/141#issuecomment-308111597

**Comment by pot-code** [comment]
@afc163 Switched to starter-kit which antd officially provided, the problem is gone ;)
