### ISSUE TITLE
这个库怎么配置才能按需加载lodash？

### ISSUE THREAD

**Issue by vipcxj** [ant-design/babel-plugin-import#140]
lodash每个函数基本都有独立模块版本，但并不是在主模块的子目录下，这个可以通过配置按需加载吗？

**Comment by afc163** [comment]
`["import", { "libraryName": "lodash", "libraryDirectory":: "" }]`

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/74#issuecomment-263740273

**Comment by vipcxj** [comment]
谢谢，我试试~

**Comment by yyfearth** [comment]
或者用现成的 `babel-plugin-lodash`
然后 `plugins: ['lodash']` 就可以le

**Comment by youngjuning** [comment]
@yyfearth  babel-plugin-lodash 需要结合 lodash-webpack-plugin。RN环境并没有webpack
