### ISSUE TITLE
Not working on create-react-app, all styles/icons are missing

### ISSUE THREAD

**Issue by ikzjfr0** [ant-design/babel-plugin-import#141]
**How to reproduce it**
step1: create-react-app: version of 1.3.0
step2: eject it
step3: strictly follow here: https://ant.design/docs/react/use-with-create-react-app-cn 

result: 
work on "yarn start"  (debug mode)
not work if "yarn build"   (product mode): no icons shows and styles are missing

my case is quite similar with : https://github.com/ant-design/babel-plugin-import/issues/139

**Comment by ikzjfr0** [comment]
You mentioned in document: "babel-plugin-import 是一个用于按需加载组件代码和样式的 babel 插件（原理），现在我们尝试安装它并修改 config/webpack.config.dev.js 文件。"

do I need to change config/webpack.config.prod.js too ?

**Comment by afc163** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/507615/27084143-5f2a8814-507d-11e7-9712-7b3610e88c84.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/507615/27084153-65728546-507d-11e7-93fc-e5174ecf4d9e.png">

**Comment by ikzjfr0** [comment]
thanks,
