### ISSUE TITLE
How to disable core style inclusion with modular import?

### ISSUE THREAD

**Issue by cloudever** [ant-design/babel-plugin-import#147]
Currenly we have a project built with react-bootstrap and recently started migration to AntDesign.

For example we have a code:
```js
import { Button } from 'antd';
```
So babel-plugin-import includes `Button`s styles with core styles such as `normalizr`, `icons` etc. Core styles seems to be located here [https://github.com/ant-design/ant-design/blob/master/components/style/core/index.less](https://github.com/ant-design/ant-design/blob/master/components/style/core/index.less)

Is there a variants to ignore core styles to solve a problem of overwriting previosly included css?

**Comment by Unforgiven-wanda** [comment]
@cloudever Did you solve this issue? And how, please?
