### ISSUE TITLE
what is difference between this one and 'babel-plugin-transform-imports'?!

### ISSUE THREAD

**Issue by plandem** [ant-design/babel-plugin-import#148]
Under the hood its same, so what is the reason for **another one** transformer?!
https://www.npmjs.com/package/babel-plugin-transform-imports

**Comment by cncolder** [comment]
Maybe bcs bitbucket

User like search something in github. If not found. Write one.

**Comment by psychobolt** [comment]
babel-plugin-import: 
  Custom path transformer with Babel7 js config
  Transform to commonjs require
babel-plugin-transform-imports: 
  Custom path transformer with a extern script file
  Transform to ES6 imports

**Comment by ssehacker** [comment]
seems like babel-plugin-transform-imports doesn't support import css.
and babel-plugin-import does not support import multiple library.
