### ISSUE TITLE
antd + antd-mobile same time

### ISSUE THREAD

**Issue by eric-muyser-hs** [ant-design/babel-plugin-import#151]
Hi,

Great plugin. I'm trying to import `antd` and `antd-mobile` at the same time and it causes this error when I have them together, but it's fine if I only have `antd-mobile`.

`antd-mobile does not contain an export named 'Button'`

Code:

```js
[
 'import',
 { libraryName: 'antd', style: true },
 { libraryName: 'antd-mobile', style: true }
]
```

This doesn't work either:

```js
[
 'import',
 { libraryName: 'antd', style: true }
],
 'import',
 { libraryName: 'antd-mobile', style: true }
],
```

Thanks in advance,
Eric

**Comment by iNikNik** [comment]
I've faced same problem last days, and solution is pretty easy:

```javascript
[
 'import', [
   { libraryName: 'antd', style: true },
   { libraryName: 'antd-mobile', style: true }
 ]
]
```

Just wrap pass configs as array

**Comment by ericmuyser** [comment]
That worked perfectly, thank you @iNikNik !!
