### ISSUE TITLE
typescript + andt 按需加载

### ISSUE THREAD

**Issue by miaowwwww** [ant-design/babel-plugin-import#156]
ts-loader 如何实现antd的按需加载？
{test: /\.tsx?/, use: ["ts-loader", "babel-loader"]}; 会报错，找不到style 
调换两个loader的顺序， 则编译成功，可是没有成功按需加载。会出现warn：babel-plugin-import

**Comment by JimmyLv** [comment]
+1

**Comment by afc163** [comment]
Try https://github.com/Brooooooklyn/ts-import-plugin

**Comment by taozhi8833998** [comment]
same with [#73](https://github.com/ant-design/babel-plugin-import/issues/73)

**Comment by gwuhaolin** [comment]
[ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 可以做到。

它是一个 babel-plugin-import 的代替品，一个 Webpack Loader，优势有：
- 性能更好；
- 能用于非 Babel 的项目，只要你的项目使用 Webpack 构建即可；

**Comment by naivefun** [comment]
@gwuhaolin  create-react-app 中如何配置这个？
