### ISSUE TITLE
shit docs & full demo wanted

### ISSUE THREAD

**Issue by xgqfrms-gildata** [ant-design/babel-plugin-import#158]
# shit docs

https://ant.design/docs/react/use-with-create-react-app-cn#使用-babel-plugin-import

> where is the `config/webpack.config.dev.js` ?

# Could you provide a full demo for us?

> it's real bad UX for us, just give a shit api doc!

# all kinds of `holes/pits`

https://github.com/gildata/RAIO/issues/35

**Comment by xgqfrms-gildata** [comment]
# .babelrc

https://babeljs.io/docs/usage/babelrc/

https://babeljs.io/docs/usage/api/#options

https://babeljs.io/docs/plugins/
https://babeljs.io/docs/plugins/preset-es2015/
https://babeljs.io/docs/plugins/preset-es2017/
https://babeljs.io/docs/plugins/preset-react/

```js
{
    "plugins": ["transform-react-jsx"],
    "ignore": [
        "foo.js",
        "bar/**/*.js"
    ],
    "presets": ["react"]
}

```

**Comment by afc163** [comment]
https://github.com/ant-design/create-react-app-antd

**Comment by afc163** [comment]
RTFM

**Comment by xgqfrms-gildata** [comment]
I really don't like it, but I have to use it for now!

**Comment by afc163** [comment]
Quit the job which force you to use `antd`.

**Comment by xgqfrms-gildata** [comment]
# Maybe, who knows!

> Great minds think alike!

http://weibo.com/afc163?is_hot=1#1501149894616

![image](https://user-images.githubusercontent.com/29531779/28665502-68df49b2-72f6-11e7-931f-022feace22ef.png)
