### ISSUE TITLE
如何配置，找不到.babelrc和babel-loader啊

### ISSUE THREAD

**Issue by bangcodes** [ant-design/babel-plugin-import#161]
现在的项目用的是create-react-app创建的，然后用npm run eject弹出了

这样的情况下，在哪里找到babel-loader, 并且把babel-plugin-import配置正确啊？

**Comment by afc163** [comment]
所以你不看文档的？https://ant.design/docs/react/use-with-create-react-app-cn#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE
