### ISSUE TITLE
ant design那个react starter kit那个分支。babel-plugin-import配置无效啊。

### ISSUE THREAD

**Issue by pengliaoye** [ant-design/babel-plugin-import#162]
// Only use babel-plugin-import in client side
clientConfig.module.rules[0].options.plugins = [
  ...clientConfig.module.rules[0].options.plugins,
  ['import', { libraryName: 'antd', style: 'css' }],
];

上面是那个分支里面的配置。

**Comment by afc163** [comment]
『无效』的具体表现是什么呢？

我本地测试是可行的。

**Comment by pengliaoye** [comment]
我运行了yarn run build -- --release。 但是打包以后。启动起来找不到Menu这个对象。

我看了vendor里面也搜索不到antd。

**Comment by afc163** [comment]
有具体的操作步骤和重现方式么？

**Comment by pengliaoye** [comment]
我是clone了最新的react starter kit,然后按你commit的代码全部修改了。在里面开发。最后打包的时候发现没import antd的js。我clone你那个分支先试一下。

**Comment by afc163** [comment]
如果有问题，麻烦提供最小可重现的代码和重现方式。

**Comment by pengliaoye** [comment]
你那个打包以后没问题，就是按钮没样式。 我引入的3个模块都是最新的。不知道是不是这个原因。

+    "antd": "^2.12.3",
+    "babel-plugin-import": "^1.3.1",
+    "style-loader": "^0.18.2",

**Comment by pengliaoye** [comment]
好像不是。我先看看吧。

**Comment by pengliaoye** [comment]
最新的react starter kit.我用yarn run build,然后用node build/server.js启动起来可以.
用yarn run build -- --release就不行了。

**Comment by afc163** [comment]
https://github.com/ant-design/react-starter-kit/commit/b52adf0992cb9aaae00c6aab1c89ecc1323f7b28#diff-2a11159a0f72e5ac0dd32dadc5f8398aR115

这里估计要补上 css-loader 。

**Comment by pengliaoye** [comment]
样式那个解决了。 
=[/node_modules\/.*antd/],
改为
=[/node_modules[/\\].*antd/], 
好像有了。网上看的。不过整体样式好像都变了。

+          {
+            test: /\.css$/,
+            include: [/node_modules[/\\].*antd/],
+            loader: 'style-loader',
+          },
+
           // Convert CSS into JS module
           {
             issuer: { not: [reStyle] },
+            exclude: [/node_modules[/\\].*antd/],

**Comment by pengliaoye** [comment]
就是这个https://github.com/ant-design/react-starter-kit/pull/1

**Comment by pengliaoye** [comment]
import { Layout as Lay, Menu, Icon } from 'antd';

是不是 as 这种语法不支持啊。我打印Layout都有。Menu就找不到了。

**Comment by pengliaoye** [comment]
// Optimize React code for the production build
             // https://github.com/thejameskyle/babel-react-optimize
-            ...(isDebug ? [] : ['react-optimize']),
+            // ...(isDebug ? [] : ['react-optimize']),

找到了应该是 react-optimize 这个有问题
