### ISSUE TITLE
Create-react-app eject + css-loader modules: true -- styles not loading

### ISSUE THREAD

**Issue by ortonomy** [ant-design/babel-plugin-import#166]
**What I did:**
Following instructions for using create-react-app with antd from  the [ant design site about using in create-react-app](https://ant.design/docs/react/use-with-create-react-app) 

**Problem:**
The styles do not load.

**My setup:**
1. create-react-app => ejected
2. css-loader => ``modules: true, localIdentName: "[name]__[local]___[hash:base64:5]"``
3. ``import { Button } from 'antd';``
4. babel-plugin-import => ``webpack.config.dev.js`` =>
```
plugins: [
  ['import', { libraryName: 'antd', style: 'css' }],
]
```

When ``css-loader`` => ``modules: false`` the antd styles load fine, but not with css modules

How can I fix this?

**Comment by ortonomy** [comment]
This issue also seems to have the same problem https://github.com/ant-design/babel-plugin-import/issues/154

**Comment by andriijas** [comment]
make 2 loaders.

```
{ test: /\.css$/,
  exclude: /\.module\.css$/;  ... }
```

```
{ test: /\.module\.css$/,
  ... }

**Comment by exced** [comment]
It only works with [Less](https://github.com/ant-design/ant-design/issues/5132#issuecomment-286747637)

**Comment by Iliyass** [comment]
@andriijas clever ! 👏

**Comment by andriijas** [comment]
@Iliyass check example app https://github.com/andriijas/create-react-app-playground using react-app-rewired wrapper around CRA.

**Comment by AsmaAshfaq219** [comment]
@ortonomy, I am stuck on this same problem. Can you please right the steps you followed that made it work?

**Comment by yesmeck** [comment]
Make sure don't enable css modules for antd's css.

**Comment by AsmaAshfaq219** [comment]
Thanks for your response @yesmeck. Can I please ask you why shouldn't I enable css-modules for antd's css?

**Comment by andriijas** [comment]
Antd doesn't use css modules

**Comment by andriijas** [comment]
No. You you can use css modules for your own styling and some overriding of antd styles where you pass a className to the antd component but the antd components it self uses regular global styles which makes it easier to target/override but for project css you most likely don't want to talk to be overridable and targetable. 

If you want to make it easy use css modules on *.module.css files and other css files just load as regular style sheets.

**Comment by AsmaAshfaq219** [comment]
Thanks @andriijas! Got it.

**Comment by joshuapinter** [comment]
Here's a good example made by the Ant Design people on how you can use integrate antd (including styles) into a **Non-Ejected** create-react-app: 

https://github.com/ant-design/create-react-app-antd

There's a handful of things they do to override the default configuration with create-react-app without ejecting it. We had to do a manual "diff" to find out what they were doing differently in order to add it to our existing create-react-app application.

Should be straight forward but let me know if you need the steps.

**Comment by christhornham** [comment]
I started with create-react-app and added css-modules by ejecting my project and editing webpack.config.dev.js and webpack.config.prod.js in the config folder.  I'm using css and not less or sass.  Can someone please help me figure out how I disable css modules for antd's css? Any help would be greatly appreciated.

test: /.css$/ in webpack.config.dev.js looks like this:

{
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                  modules: true,
                  localIdentName: '[name]__[local]__[hash:base64:5]'
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },

and test: /\.css$/, in webpack.config.prod.js looks like this: 

{
            test: /\.css$/,
            loader: ExtractTextPlugin.extract(
              Object.assign(
                {
                  fallback: {
                    loader: require.resolve('style-loader'),
                    options: {
                      hmr: false,
                    },
                  },
                  use: [
                    {
                      loader: require.resolve('css-loader'),
                      options: {
                        importLoaders: 1,
                        modules: true,
                        localIdentName: '[name]__[local]__[hash:base64:5]'
                        minimize: true,
                        sourceMap: shouldUseSourceMap,
                      },
                    },
                    {
                      loader: require.resolve('postcss-loader'),
                      options: {
                        // Necessary for external CSS imports to work
                        // https://github.com/facebookincubator/create-react-app/issues/2677
                        ident: 'postcss',
                        plugins: () => [
                          require('postcss-flexbugs-fixes'),
                          autoprefixer({
                            browsers: [
                              '>1%',
                              'last 4 versions',
                              'Firefox ESR',
                              'not ie < 9', // React doesn't support IE8 anyway
                            ],
                            flexbox: 'no-2009',
                          }),
                        ],
                      },
                    },
                  ],
                },
                extractTextPluginOptions
              )
            ),
            // Note: this won't work without `new ExtractTextPlugin()` in `plugins`.
          },

Thanks!

**Comment by AsmaAshfaq219** [comment]
Hey I used react-app-rewire-css-modules. It is by codebandits I guess. Also had to do changes in config-override.js. I hope it helps you. I have a project on github by the name burger-builder. You can see the changes I did. 
I started the same way you did and had to experiment with a lot of things to get it done.

**Comment by christhornham** [comment]
It sounds like you took Max's React course on Udemy as well.  I'll start by taking a look at your project.  Thank you.

**Comment by AsmaAshfaq219** [comment]
Haha yes.

**Comment by davidfurlong** [comment]
Ok because this still wasn't clear to me after all the comments I'm writing my solution:

```js
resolve:   {
   extensions: ['.json', '.js', '.jsx', '.css'], // add css so we can resolve the css files in node_modules/antd
...
}
```

```js
// Only local imports of scss files are using css modules, all other files are without css modules (required to get antd imports to work)
// Note that I could combine rules 1 and 2, although I want to make it clear that in the future I can change
// one without the other, with clear distinction of required setup
{
        test: /antd.*\.css$/,
        use: ExtractCssChunks.extract({
          fallback: 'style-loader',
          use: [
            'css-loader',
            {
              loader: 'postcss-loader',
              options: {
                config: {
                  path: './postcss.config.js',
                },
              },
            },
          ],
        }),
      },
      {
        test: /\.css$/,
        exclude: /antd.*\.css$/,
        use: ExtractCssChunks.extract({
          fallback: 'style-loader',
          use: [
            'css-loader',
            {
              loader: 'postcss-loader',
              options: {
                config: {
                  path: './postcss.config.js',
                },
              },
            },
          ],
        }),
      },
      {
        test: /\.scss$/,
        use: ExtractCssChunks.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                modules: true,
                localIdentName: '[name]__[local]',
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                config: {
                  path: './postcss.config.js',
                },
              },
            },
            'sass-loader',
          ],
        }),
      },
```

```
// babelrc

"plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": "css"
      }
    ]
}
```

Because we use babel-plugin-import with style "css" it means it will transform it to import the .css files. If you have true there then your loader needs to match .less files and transform those.

**Comment by ifeanyidavid** [comment]
@davidfurlong Thanks so much. Your solution is the only one that has worked after days of scouring the internet.

**Comment by Downchuck** [comment]
Other potential direction, for wiring up a locale (seems unlikely to work):
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc

**Comment by YanaKopyshchyk** [comment]
@davidfurlong Thank you! Work for me perfect!

**Comment by LiudmilaE** [comment]
@davidfurlong  Thank you SO MUCH! Work as a charm!

**Comment by ayepRahman** [comment]
@davidfurlong Awesome!!!, Work for me perfectly, But can you add config webpack prod build instead?

**Comment by davidfurlong** [comment]
@ayepRahman prod config; I think that the syntax for ExtractCssChunks loader has changed slightly since my last post, but I think prod is the same for the parts mentioned above
```js
{
        test: /antd.*\.css$/,
        use: [
          ExtractCssChunks.loader,
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './postcss.config.js',
              },
            },
          },
        ],
      },
      {
        test: /\.css$/,
        exclude: /antd.*\.css$/,
        use: [
          ExtractCssChunks.loader,
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './postcss.config.js',
              },
            },
          },
        ],
      },
      {
        test: /\.scss$/,
        use: [
          ExtractCssChunks.loader,
          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[name]__[local]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './postcss.config.js',
              },
            },
          },
          'sass-loader',
        ],
      },
      {
        test: /\.less$/,
        use: [
          ExtractCssChunks.loader,
          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[name]__[local]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './postcss.config.js',
              },
            },
          },
          'less-loader',
        ],
      },
```

**Comment by gabrielcarneiro97** [comment]
hey @davidfurlong I'm trying to use your solution, but I don't know a lot about webpack. You used a postcss.config.js, could you show this file?

**Comment by davidfurlong** [comment]
Postcss is an optional post processor, you can safely remove that loader. I would, but since this we've removed postcss from our codebase and I don't think it'd be useful. It was probably a generic config from https://github.com/postcss/postcss-loader
