### ISSUE TITLE
`yarn add` causes ["import", {}] to be removed from .babelrc

### ISSUE THREAD

**Issue by davidhatten** [ant-design/babel-plugin-import#170]
Adding a new dependency with yarn will cause this line in `plugins` to disappear. 

You can use `yarn add react-native-svg` to induce it, but it should work with any library.

I'm not sure if the problem is antd or yarn, but I've replicated this on both Mac and Bash on Ubuntu on Windows.

**Comment by yesmeck** [comment]
You should file an issue to yarn's repo.
