### ISSUE TITLE
options can not be an array. Expected one of string, object

### ISSUE THREAD

**Issue by WangYang-Rex** [ant-design/babel-plugin-import#182]
I want to import antd & antd-mobile，but it seems that options can not be an array, it's expected one of string, object

![image](https://user-images.githubusercontent.com/7553998/31209224-2e6d2666-a94f-11e7-8b54-09ad05021a05.png)

**Comment by Alexorz** [comment]
+1

**Comment by yesmeck** [comment]
Which lint tool do you use?

**Comment by Adam23** [comment]
+ 1

**Comment by yukinight** [comment]
+1，有人解决吗

**Comment by Yufeikang** [comment]
已解决 https://github.com/ant-design/babel-plugin-import/issues/217
