### ISSUE TITLE
what's the difference between style: true and style:css ? And which scheme to use is better？

### ISSUE THREAD

**Issue by chenDiDi** [ant-design/babel-plugin-import#191]
what's the difference between style: true and style:css ?
![image](https://user-images.githubusercontent.com/19472038/33536964-9872ae54-d8f3-11e7-8009-2ab58cc51947.png)
![image](https://user-images.githubusercontent.com/19472038/33536967-9d7f3f98-d8f3-11e7-84a2-99d7ac576a64.png)
As the figure above shows the screenshot from the official document, two methods of using the method required one CSS resource file, one is the less/sass resource file。
Is it better to use a ? Because of the less／sass file, using the advantages of CSS preprocessor, and the compatibility is good, and I see that others sad the file size is smaller after the project is built _ [https://github.com/ant-design/babel-plugin-import/issues/165](url)

**Comment by cfrank-rv** [comment]
The `style` rule is defining where `babel-plugin-import` looks for styles. If it is set to `true` it imports files directly from the root of the component which you are importing, if it is set to a `string` it looks for a folder of that name and imports the styles from there. You can also pass in a `function`. And `babel-plugin-import` will look for styles in whichever place is returned by the function.
