### ISSUE TITLE
Does this plugin can only be used for antd?

### ISSUE THREAD

**Issue by JHanLu** [ant-design/babel-plugin-import#193]

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import#options

**Comment by JHanLu** [comment]
@afc163 Does the third party library has to meet certain requierment in file structure?

**Comment by afc163** [comment]
There is a undocumented feature `customName`: https://github.com/ant-design/babel-plugin-import/pull/163

**Comment by JHanLu** [comment]
@afc163 Thanks
