### ISSUE TITLE
react-app-rewire support

### ISSUE THREAD

**Issue by brianveltman** [ant-design/babel-plugin-import#201]
I added a react-app-rewire-import plugin to use the babel plugin without ejecting from `create-react-app`.

Feel free to use it https://github.com/brianveltman/react-app-rewire-import

**Comment by brianveltman** [comment]
refs #166

**Comment by abenhamdine** [comment]
Why not use injectBabelPlugin ?

example : 
```ts
const { injectBabelPlugin } = require('react-app-rewired')
...
config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config)
