### ISSUE TITLE
create-react-app使用babel-plugin-import报错,dev环境和production都出现less引入错误

### ISSUE THREAD

**Issue by sex-squirrel** [ant-design/babel-plugin-import#213]
专门创建一个demo,使用最原始的配置,加上less,配置如下:
![7df228d6-9510-408f-b679-f84d7e2a6bf3](https://user-images.githubusercontent.com/24666536/36934454-b808a5c6-1f24-11e8-849b-15358026da37.png)
![e2ab5e86-e893-437d-b2ce-4f62b8fec8d3](https://user-images.githubusercontent.com/24666536/36934456-c25d0a62-1f24-11e8-974d-93886fdd4256.png)
按需引入如下:
![d58309c9-7a54-4d94-a1c4-b7760862db16](https://user-images.githubusercontent.com/24666536/36934462-da65af10-1f24-11e8-8580-810c4c33f1ad.png)
错误如下:
![09a2739d-a961-49af-9cff-f6a1f34bd12d](https://user-images.githubusercontent.com/24666536/36934471-f8894524-1f24-11e8-90cb-649188568853.png)
![9adfcbf5-08c5-4302-a95e-4ef85b5200a0](https://user-images.githubusercontent.com/24666536/36934472-f8ca1b3a-1f24-11e8-8f21-34145c758fe5.png)

备注: 配置所选库
"antd": "^3.2.3",
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.1.0",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.2.0",
    "react-dev-utils": "^5.0.0",
    "react-dom": "^16.2.0",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
    "babel-plugin-import": "^1.6.5",
    "less": "^3.0.1",
    "less-loader": "^4.0.6"

**Comment by yesmeck** [comment]
看起来跟 `babel-plugin-import` 没关系，建议自己排查下。

**Comment by sex-squirrel** [comment]
若style:"css",则正常显示,就加了这么一个配置

**Comment by yesmeck** [comment]
再检查下  less-loader 配置，自己写个 less 试试。

**Comment by sex-squirrel** [comment]
好吧,若style: "css", 我自己的less可以被正常解析,在手上的项目中好像也有这个问题,改为css就正常了,自己没有找到答案,所以求助一下各位DD

**Comment by sex-squirrel** [comment]
找到了答案,大佬就是大佬,果然less-loader的问题,看了一下文档和搜索一下问题,下面是配置:
![24db10d9-8b8b-48d9-8d5c-0ff99f928521](https://user-images.githubusercontent.com/24666536/36960259-226cf48c-2081-11e8-912c-23445c504ea9.png)
遇到Inline JavaScript is not enabled. Is it set in your options?的问题请参考[https://github.com/ant-design/ant-design/issues/7927](url)
