### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Module parse failed: Unexpected character '@'

### ISSUE THREAD

**Issue by skxiaoniao** [ant-design/babel-plugin-import#223]
THE EXCEPTION CONTENT:
ERROR 2018-04-02 09:10:39,998 [29   ] Microsoft.AspNetCore.NodeServices        - (node:2572) UnhandledPromiseRejectionWarning: Error: Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
| /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors */
ERROR 2018-04-02 09:10:40,025 [29   ] Microsoft.AspNetCore.NodeServices        - 
| /* stylelint-disable at-rule-no-unknown */
ERROR 2018-04-02 09:10:40,029 [29   ] Microsoft.AspNetCore.NodeServices        - 
| @font-face {
ERROR 2018-04-02 09:10:40,032 [29   ] Microsoft.AspNetCore.NodeServices        - 
|   font-family: "Monospaced Number";
ERROR 2018-04-02 09:10:40,036 [29   ] Microsoft.AspNetCore.NodeServices        - 
|   src: local("Tahoma");
ERROR 2018-04-02 09:10:40,043 [14   ] Microsoft.AspNetCore.NodeServices        - 
    at Object.<anonymous> (D:\projects\JKC.Video\JKC.Video.WebApi\ClientApp\dist\ui-Home.chunk.js:695:7)
    at __webpack_require__ (D:\projects\JKC.Video\JKC.Video.WebApi\ClientApp\dist\main-server.js:26:30)
    at Object.<anonymous> (D:\projects\JKC.Video\JKC.Video.WebApi\ClientApp\dist\ui-Home.chunk.js:19968:75)
    at __webpack_require__ (D:\projects\JKC.Video\JKC.Video.WebApi\ClientApp\dist\main-server.js:26:30)
    at Object.exports.modules.Array.concat.exports.__esModule (D:\projects\JKC.Video\JKC.Video.WebApi\ClientApp\dist\ui-Home.chunk.js:11:84)
    at __webpack_require__ (D:\projects\JKC.Video\JKC.Video.WebApi\ClientApp\dist\main-server.js:26:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

this is my webpack config

const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const CompressionWebpackPlugin = require('compression-webpack-plugin');
const { ReactLoadablePlugin } = require('react-loadable/webpack');
const tsImportPluginFactory = require('ts-import-plugin');
const merge = require('webpack-merge');

module.exports = (env) => {
    const isDevBuild = !(env && env.prod);

    // Configuration in common to both client-side and server-side bundles
    const sharedConfig = () => ({
        stats: { modules: false },
        resolve: { extensions: ['.js', '.jsx', '.ts', '.tsx'] },
        output: {
            filename: '[name].js',
            chunkFilename: "ui-[name].chunk.js",
            publicPath: '/dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
        },
        module: {
            rules: [
                {
                    test: /\.tsx?$/, include: /ClientApp/, use: [
                        {
                            loader: 'ts-loader',
                            options: {
                                transpileOnly: true,
                                getCustomTransformers: () => ({
                                    before: [
                                        tsImportPluginFactory({
                                            libraryName: 'antd',
                                            libraryDirectory: 'es',
                                            style: 'css'
                                        })
                                    ]
                                })
                            }
                        }
                    ]
                },
                { test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/, use: 'url-loader?limit=8192&name=images/[name].[ext]',exclude: /node_modules/ },
                { test: /\.(eot|ttf)$/, loader: 'file-loader?limit=100000' }              
            ]
        },
        plugins: [
            new CheckerPlugin(),
            new ForkTsCheckerWebpackPlugin()
        ]
    });

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig(), {
        entry: {
            'main-client': './ClientApp/boot-client.tsx',
            'react': ['react', 'react-dom', 'react-router', 'react-redux', 'react-router-redux']
        },
        module: {
            rules: [
                { test: /\.css$/, use: ExtractTextPlugin.extract({ fallback: 'style-loader',  use: isDevBuild ? 'css-loader' : 'css-loader?minimize' }) }
            ]
        },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        plugins: [
            new ExtractTextPlugin("[name].css"),
            new webpack.optimize.CommonsChunkPlugin({
                names: ['main-client', 'react'], // needed to put webpack bootstrap code before chunks
                filename: '[name].js',
                minChunks: Infinity,
                children: true
            }),
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            }),
            new ReactLoadablePlugin({
                filename: path.join(__dirname, './ClientApp/dist/react-loadable.json')
            }),
            new CompressionWebpackPlugin({ //gzip 压缩
                asset: '[path].gz[query]',
                algorithm: 'gzip',
                test: new RegExp(
                    '\\.(js|css)$'    //压缩 js 与 css
                ),
                threshold: 10240,
                minRatio: 0.8
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Plugins that apply in production builds only
            new webpack.optimize.UglifyJsPlugin()
        ])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverBundleConfig = merge(sharedConfig(), {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot-server.tsx' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            }),
            new CompressionWebpackPlugin({ //gzip 压缩
                asset: '[path].gz[query]',
                algorithm: 'gzip',
                test: new RegExp(
                    '\\.(js)$'    //压缩 js 与 css
                ),
                threshold: 10240,
                minRatio: 0.8
            })
        ],
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },
        target: 'node',
        devtool: 'inline-source-map'
    });

    return [clientBundleConfig, serverBundleConfig];
};

**Comment by yesmeck** [comment]
> You may need an appropriate loader to handle this file type.


Check your `css-loader`.
