### ISSUE TITLE
Warning: React.createElement: type is invalid when using Webpack 4

### ISSUE THREAD

**Issue by happypandaa** [ant-design/babel-plugin-import#231]

**Comment by ejoc** [comment]
Could you solve it? i have same error

**Comment by yesmeck** [comment]
Could you provide a minimal reproduce repo?

**Comment by ejoc** [comment]
https://github.com/ejoc/razzle-with-after-antd
`import { Button } from 'antd' // doesn't work
// import Button from 'antd/lib/button' // it work but without styles`

**Comment by guxingke201** [comment]
`exports.__esModule = true;`
这段代码丢失了

**Comment by guxingke201** [comment]
babel-loader不把node-modules排除，可以解决这个问题

**Comment by liuyan0535** [comment]
have the same error when i import antD-mobille components.
webpack: 4.16.5
babel-plugin-import:  1.8.0

and @guxingke201 it does not work for me. can you show detailedly? thx.

**Comment by liuyan0535** [comment]
thanks a lot.
I had resolved my problem. It's because when I upgrade webpack from v3, I forgot to delete webpack.optimize.ModuleConcatenationPlugin.
