### ISSUE TITLE
importing both antd and antd-mobile doesn't work

### ISSUE THREAD

**Issue by enzeberg** [ant-design/babel-plugin-import#233]
I'm using `antd` and `antd-mobile` in my project. Here are my related configurations:
```
"plugins": [
    [
      "import",
      [
        {
          "libraryName": "antd",
          "style": true
        },
        {
          "libraryName": "antd-mobile",
          "style": true
        }
      ]
    ]
  ]
```
The desktop page is normal, but the mobile page is not.
If I I remove `{ "libraryName": "antd", "style": true },`, the mobile page will behave normally.

Does anyone have a solution for this problem?

**Comment by afc163** [comment]
@sorrycc Why this method not working any more?

**Comment by ToadWoo** [comment]
I'm  has this problem too

**Comment by AleksRedman** [comment]
https://github.com/ant-design/babel-plugin-import

> 
Options can't be an array in babel@7+, but you can add plugins with name to support multiple dependencies.

For Example:

// .babelrc
"plugins": [
  ["import", { "libraryName": "antd", "libraryDirectory": "lib"}, "ant"],
  ["import", { "libraryName": "ant-mobile", "libraryDirectory": "lib"}, "ant-mobile"]
]
>

**Comment by enzeberg** [comment]
@AleksRedman I did what you said. But it still didn't work.

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import#options

**Comment by dazjean** [comment]
so ...that is means  we want to suport multiple dependencies must beUpgrade to Babel 7?
