### ISSUE TITLE
if option style is Function, .babelrc will throw syntax error

### ISSUE THREAD

**Issue by ShanaMaid** [ant-design/babel-plugin-import#234]
![image](https://user-images.githubusercontent.com/20333903/39863190-8a24b436-5478-11e8-91a3-9af5df97f495.png)

**Comment by yesmeck** [comment]
You can not use function in JSON, see https://github.com/ant-design/babel-plugin-import/pull/221#issuecomment-379533231

**Comment by ShanaMaid** [comment]
@yesmeck thx
