### ISSUE TITLE
babel7 不支持数组格式的 plugin options

### ISSUE THREAD

**Issue by wuomzfx** [ant-design/babel-plugin-import#238]
![image](https://user-images.githubusercontent.com/8017237/40399187-7c3efb06-5e6e-11e8-8c37-29cf85965315.png)

文档需要对应更新一下

babel 相关源码：https://github.com/babel/babel/blob/master/packages/babel-core/src/config/validation/option-assertions.js#L243

**Comment by brandonhall** [comment]
We're running into the same issue. Currently, the plugin can only be used with one dependency.

**Comment by wuomzfx** [comment]
@brandonhall you can add this plugin twice with name ,like:

```javascript
plugins: [
  [ 'import', { libraryName: 'ant-design', libraryDirectory: 'lib', }, 'ant' ],
  [ 'import', { libraryName: 'ant-design-mobile', libraryDirectory: 'lib', }, 'ant-mobile' ],
]
```

**Comment by afc163** [comment]
PR is welcome~

**Comment by stkevintan** [comment]
> @brandonhall you can add this plugin twice with name ,like:
> 
> ```js
> plugins: [
>   [ 'import', { libraryName: 'ant-design', libraryDirectory: 'lib', }, 'ant' ],
>   [ 'import', { libraryName: 'ant-design-mobile', libraryDirectory: 'lib', }, 'ant-mobile' ],
> ]
> ```

Is not going to work. the second config will be ignore everytime.
