### ISSUE TITLE
customName 是怎么使用的

### ISSUE THREAD

**Issue by codcer** [ant-design/babel-plugin-import#250]

**Comment by codcer** [comment]
打包之后生成lib后  ，功能按类型分的 string类，urls类，。。。 ['import', {
      libraryName: 'ffll',
      camel2UnderlineComponentName: false,
      camel2DashComponentName: false,
      customName(name) {
        if (!map[name]) {
          return false;
        }
        return `lib/${map[name]}`;
      },
    }],

**Comment by yesmeck** [comment]
请参考 README
