### ISSUE TITLE
按需加载antd的js问题

### ISSUE THREAD

**Issue by imdoge** [ant-design/babel-plugin-import#253]
"antd": "^3.7.0",
"babel-loader": "^7.1.1",
"babel-plugin-import": "^1.8.0",
"babel-plugin-transform-runtime": "^6.23.0"

之前同一个项目按需加载没错误，最近发现在更新库版本之后有问题（不清楚是哪个库和版本的问题）
css/less成功按需加载，但js总是全部加载
测试发现antd/es/index.js也被加载了，这是个包含所有组件的，我尝试把antd/es/index.js里的内容全清空，发现成功按需加载而且没报错
是否我使用方式的问题还是上面的猜测？

**Comment by imdoge** [comment]
是否除了单独组件以外，把antd/es/index.js也加载了

**Comment by wufeng87** [comment]
@imdoge 遇到了同样的问题，最终有解决办法了吗
