### ISSUE TITLE
插件错误替换了局部作用域里的变量

### ISSUE THREAD

**Issue by stkevintan** [ant-design/babel-plugin-import#274]
```js
import {message} from 'antd'

showInfo = (message, type = 'error') => {
   if (typeof message === 'object') {
      message = _.cloneDeep(message)
      console.log(message)
      console.log(Object.entries(message).find(m => m[0] === 'msg'))
      console.log(Object.getOwnPropertyDescriptor(message, 'msg'))
      console.log(message.msg)
      console.log(message.success)
    }
   // .....
}
```
在console中的数据结果如图：

![image](https://user-images.githubusercontent.com/5887203/46205865-d7345380-c354-11e8-9de0-a429d84c46cf.png)

可以看到，直接`console.log(message)`输出的是函数局部作用域里的message， 但是如果访问message里面的属性时，(如`console.log(message.msg)`）输出到是antd的message,所以`message.msg`为undefined，`message.success`反而为一个函数。

当直接使用下列语法import的时候，问题不复存在：
```js
import message from 'antd/lib/message'
```

因此，十有八九是`babel-plugin-import`的问题

**Comment by ssehacker** [comment]
+1， 我也遇到了，确定是babel-plugin-import问题。
