### ISSUE TITLE
Multiple configuration files found. package.json#babel  - .babelrc

### ISSUE THREAD

**Issue by alimot22** [ant-design/babel-plugin-import#291]
I want to use automatically import stylesheets and as the document said, I've created a .babelrc file and write 
{
  "plugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }] // `style: true` for less
  ]
}
into the file. But i'm getting an error:

Error: Multiple configuration files found. Please remove one:
 - package.json#babel
 - .babelrc

By the way, I'm using create-react-app

**Comment by janouser11** [comment]
I have the same issue

**Comment by pkrefta** [comment]
You can guys safely remove `.babelrc` file and then add it contents to `babel` key in `package.json`

**Comment by Way-U-Need** [comment]
+1

**Comment by Carrie999** [comment]
+10086

**Comment by LuigiCaradonna** [comment]
Look at your package.json file for the lines

`"babel": {
    "presets": [
      "react-app"
    ]
}`

and remove them

**Comment by ebarracchia** [comment]
I added all the configuration into package.json and after that I removed .babelrc file.

Now is working now!!!

**Comment by huge689** [comment]
I have the same problem and have not solved it by the above method.

**Comment by trojanchris** [comment]
I had this issue and the cause was that I had package-lock creation disabled globally for my npm

running:
npm config set package-lock true

and removing:
package-lock=false

from my ~/.npmrc, then re-running npm install and building worked for me

**Comment by hllinc** [comment]
This problem is caused by that both the .babelrc file and the babel props in package.json file all exist, delete one of them to fixed.
