### ISSUE TITLE
libraryName可以指定本地文件吗

### ISSUE THREAD

**Issue by 184609680** [ant-design/babel-plugin-import#292]
libraryName可以指定本地文件吗

**Comment by denglai** [comment]
libraryName can point to a local file??????????????????

**Comment by 364734461** [comment]
可以

**Comment by lifetin** [comment]
怎么指向本地的链接呀. 可能暂时开发的不传到npm或是git,只在本地用, 不知道怎么引用

**Comment by yesmeck** [comment]
可以通过 `customName` 自定义。
