### ISSUE TITLE
.babelrc文件在什么地方？

### ISSUE THREAD

**Issue by zwl1619** [ant-design/babel-plugin-import#294]
.babelrc文件在什么地方？
使用create-react-app脚手架，没有找到.babelrc文件，自己添加吗？添加在什么地方？
![image](https://user-images.githubusercontent.com/13177997/50067527-3723f300-01fc-11e9-88d4-4164c9bf4ecb.png)

**Comment by pssgo** [comment]
add .babelrc on root dir

**Comment by Ryuurock** [comment]
在package.json的“babel”字段下

**Comment by x93008** [comment]
请问一下，这个配置可以放在webpack.config.js中吗？
