### ISSUE TITLE
部分组件按需加载样式style报错，求解

### ISSUE THREAD

**Issue by TigerHee** [ant-design/babel-plugin-import#295]
使用create-react-app脚手架，babel-plugin-import配置按需加载
*****************package.json*******************
`"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
        "import",
        {
          "libraryName": "antd",
          "style": "css"
        }
      ]
    ]
  },`
************************************************
大部分组件可以加载，但是当使用Table，Spin时报错：
use：import { Spin } from 'antd';
---------------------------------------------------------
./node_modules/_antd@3.10.8@antd/lib/spin/style/index.css (./node_modules/_css-loader@1.0.0@css-loader??ref--7-oneOf-3-1!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_antd@3.10.8@antd/lib/spin/style/index.css)

  /* autoprefixer: off */
  filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
                                                             ^
Unrecognised input
      in D:\tigerWork\b2bweb\node_modules\_antd@3.10.8@antd\lib\spin\style\index.css (line 98, column 63)
----------------------------------------------------------
然后将Table采用如下方式可行，Spin依然报错：
  import Tablefrom 'antd/lib/table';
  import 'antd/lib/table/style/index.css';

**Comment by flftfqwxf** [comment]
我在把less升级为3.0以上时，style:true时，就会报错，ant-mobile版本为2.x版本

**Comment by flftfqwxf** [comment]
这个项目好象很久没人维护了，我网上看了些，很多人遇到类似问题，在less升级到3.x以上各种报错
