### ISSUE TITLE
webpack 版本4.28.3， antd v3.11.6, babel7 按需加载无效

### ISSUE THREAD

**Issue by Hyg900928** [ant-design/babel-plugin-import#298]
我的babel配置如下：typescript 版本是v3.2.2
![image](https://user-images.githubusercontent.com/19190553/50813421-4573b380-1351-11e9-9136-df1f438ab1d2.png)
启动之后样式没有生效：
![image](https://user-images.githubusercontent.com/19190553/50813453-61775500-1351-11e9-9a32-095dfa2a7e44.png)

**Comment by Hyg900928** [comment]
查了好久的资料都没有解决， 这个问题网上说的用ts-import-plugin 解决我也试了，但是还是无效
![image](https://user-images.githubusercontent.com/19190553/50813661-1447b300-1352-11e9-8848-4f989db327e8.png)
![image](https://user-images.githubusercontent.com/19190553/50813674-1e69b180-1352-11e9-9428-bcf6eb9d4851.png)

**Comment by afc163** [comment]
```diff
- styles
+ style
```

**Comment by Hyg900928** [comment]
@afc163 改了，还是无效
![image](https://user-images.githubusercontent.com/19190553/50823948-3d773c00-1370-11e9-9659-e537499e360e.png)

**Comment by Hyg900928** [comment]
我的tsconfig.json 配置如下，不知道是不是我的ts配置有问题啊
![image](https://user-images.githubusercontent.com/19190553/50868823-3e4db380-13ec-11e9-8bf8-488482ce8582.png)

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/73#issuecomment-277881436

**Comment by Hyg900928** [comment]
@afc163 我已经按照你的意思改了， 按需加载还是无效，tsconfg.json 配置如下：

![image](https://user-images.githubusercontent.com/19190553/50884801-e84a3180-1426-11e9-8b39-f53ddaa58138.png)

代码如下：

![image](https://user-images.githubusercontent.com/19190553/50884865-0d3ea480-1427-11e9-9371-5454e03ae80e.png)

执行结果如下：

![image](https://user-images.githubusercontent.com/19190553/50884887-20517480-1427-11e9-96bd-2135ef79eead.png)

**Comment by Hyg900928** [comment]
没有任何的报错信息

**Comment by Hyg900928** [comment]
@afc163 @sorrycc  webpack 部分配置如下：
![image](https://user-images.githubusercontent.com/19190553/50885552-fbf69780-1428-11e9-9bc0-5794370eba7a.png)
![image](https://user-images.githubusercontent.com/19190553/50885569-0749c300-1429-11e9-802f-08e746e4e55a.png)

**Comment by Hyg900928** [comment]
如果我自入口处引入css 文件， 样式就可以出来了
![image](https://user-images.githubusercontent.com/19190553/50886676-01091600-142c-11e9-9191-84e827db682b.png)

但是这样的话，不是把整个css 文件都加载过来了吗，就不符合按需加载了吧？

**Comment by Hyg900928** [comment]
@afc163 麻烦给讲解一下啦

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi-examples/blob/master/typescript/tsconfig.json 配 tsconfig.json 试试，需要确保文件交给 babel-plugin-import 之前是 esm 的。

**Comment by summer789** [comment]
@afc163  @sorrycc 我现在也遇到这个问题了 babel7 以后，可以直接用babel来处理typescript ，  上面提到的方法都试过，完全没用，

**Comment by summer789** [comment]
@Hyg900928  问题解决了吗

**Comment by summer789** [comment]
@Hyg900928  
这样配置以后，正常了，你试试
![Uploading 1547464943374.jpg…]()

**Comment by summer789** [comment]
这样配置以后，正常了，你试试
@Hyg900928 
![1547464943374](https://user-images.githubusercontent.com/20252366/51110034-0f8f6d00-1832-11e9-98d8-97fe558ce401.jpg)

**Comment by Hyg900928** [comment]
@summer789 能截一下，完整的图吗， 我这边还没解决啊

**Comment by Hyg900928** [comment]
@summer789 或者给个参考地址也行

**Comment by Hyg900928** [comment]
已经解决， 需要用awesome-typescript-loader  处理一次 ，然后在交给babel-loader, 这样就可以解决
![image](https://user-images.githubusercontent.com/19190553/51155855-fc24e600-18b3-11e9-9f5a-f28c1e7b85f2.png)

**Comment by es3154** [comment]
@Hyg900928 可以把你的完整配置发一份吗？我也遇到同样的问题

**Comment by es3154** [comment]
babel7 使用ts 使用@babel/preset-typescript
参考这个配置[https://github.com/microsoft/TypeScript-Babel-Starter](url)
[https://juejin.im/post/5c822e426fb9a04a0a5ffb49](url)

**Comment by kokoroX** [comment]
> babel7 使用ts 使用@babel/preset-typescript
> 参考这个配置[https://github.com/microsoft/TypeScript-Babel-Starter](url)
> [https://juejin.im/post/5c822e426fb9a04a0a5ffb49](url)

解决了吗
