### ISSUE TITLE
使用express服务端渲染，如果babel中配置了import会报错，删掉就可以正常启动

### ISSUE THREAD

**Issue by Shurlormes** [ant-design/babel-plugin-import#302]
[使用express服务端渲染，如果babel中配置了import会报错，删掉就可以正常启动。
但是这个配置，用webpack，不管是devServer，还是编译文件，都正常。只有在尝试ssr的时候会包错
```
就是在.babelrc文件中的plugins的这段代码：

[
	"import",
	{
		"libraryName": "antd",
		"libraryDirectory": "es",
		"style": true
	}
]
```

```
(function (exports, require, module, __filename, __dirname) { import '../../style/index.less';
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
...
```

我的相关配置文件:
.babel
```
{
	"presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [
		"@babel/plugin-proposal-object-rest-spread",
		"@babel/plugin-transform-runtime",
		[
			"import",
			{
				"libraryName": "antd",
				"libraryDirectory": "es",
				"style": true
			}
		]
	]
}
```

server.js
```
require('ignore-styles');
var fs = require('fs');
var babelConfig = JSON.parse(fs.readFileSync('./.babelrc'));
require('@babel/register')(babelConfig);

require('./express.js');
```

express.js
```
import path from 'path';
import fs from 'fs';
import express from 'express';
import React from 'react';
import {renderToString} from 'react-dom/server';
import {StaticRouter} from 'react-router-dom';
import Home from './src/component/Home';
const ROOT_PATH = path.resolve(__dirname);
const BUILD_PATH = path.resolve(ROOT_PATH, 'build');
const app = express();

app.use(express.static(BUILD_PATH));
app.use('*', function (req, res) {
	let context = {};
	const template = renderToString(
		<StaticRouter location={req.url} context={context}>
			<Home/>
		</StaticRouter>
	);
	if(context.status === 404) {
		res.status(404);
	}
	fs.readFile(path.resolve(BUILD_PATH + '/index.html'), 'utf8', (err, data) => {
		if (err) {
			console.error(err);
			return res.status(500).send('An error occurred');
		}
		return res.send(
			data.replace('<div id="root"></div>', `<div id="root">${template}</div>`)
		)
	});
});

const server = app.listen(3000, () => {
	const host = server.address().address;
	const port = server.address().port;
	console.log('server is start at', host, port);
});
```

启动 node ./server.js

**Comment by zry754331875** [comment]
我有类似的问题，不过我用的是razzle

**Comment by zry754331875** [comment]
(function (exports, require, module, __filename, __dirname) { @import './themes/default';

**Comment by Shurlormes** [comment]
没有人看下吗? @sorrycc   @afc163  @yesmeck

**Comment by Limsanity** [comment]
使用服务端渲染要符合commonjs，因此`.babelrc`中的`"libraryDirectory":"es"`配置要变为`"libraryDirectory":"lib"`。

**Comment by Limsanity** [comment]
`babel-plugin-import`相关配置中的`libraryDirectory`配置改为：`"libraryDirectory": "lib"`。
webpack.server.config.js中的`externals`配置改为：
```js
externals: nodeExternals({
    whitelist: /ant-design-vue\/lib\/(.)+\/style\/css/
}),
```
因为该babel插件将
```js
import { DatePicker } from 'antd';
```
转换为
```js
import DatePicker from 'antd/lib/date-picker'; 
import 'antd/lib/date-picker/style/css';
```
其中`'antd/lib/date-picker/style/css'`中的css是一个js文件，而不是css文件，所以如果externals的白名单设置为`/\.css$/`并不会生效，因此将白名单设为上面的形式才能正确处理css文件。

**Comment by bowencool** [comment]
我也是

**Comment by MichaelIT** [comment]
可以参考next.js的配置试试：
`
    if (isServer) {
      const antStyles = /(antd|antd-mobile)\/.*?\/style.*?/;
      const origExternals = [...webpackConfig.externals];
      webpackConfig.externals = [
        (context, request, callback) => {
          if (request.match(antStyles)) {
            return callback();
          }
          if (typeof origExternals[0] === 'function') {
            origExternals[0](context, request, callback);
          } else {
            callback();
          }
        },
        ...(typeof origExternals[0] === 'function' ? [] : origExternals),
      ];

      webpackConfig.module.rules.unshift({
        test: antStyles,
        use: 'null-loader',
      });
    }`

**Comment by harshithmullapudi** [comment]
Hey any update on this ?

**Comment by Thyiad** [comment]
@harshithmullapudi 
just as Limsanity  said, you need update your config, and my externals config is like this:
`externals: isServer
            ? [
                  nodeExternals({
                    allowlist: [
                          /\.(eot|woff|woff2|ttf|otf)$/,
                          /\.(svg|png|jpg|jpeg|gif|ico)$/,
                          /\.(mp4|mp3|ogg|swf|webp)$/,
                          /\.(css|scss|sass|sss|less)$/,
                          /antd\/.*?\/style.*?/,
                      ].filter((x) => x),
                  }),
              ]
            : [],`

**Comment by gdabs** [comment]
externals: nodeExternals({
    whitelist: [/antd\/.*?\/style.*?/,/\.(css|less|sass|scss)$/],
    modulesDir: paths.appNodeModules,
  }),

**Comment by gdabs** [comment]
externals: nodeExternals({
    whitelist: [/antd\/.*?\/style.*?/,/\.(css|less|sass|scss)$/],
    modulesDir: paths.appNodeModules,
  }),

**Comment by gdabs** [comment]
[ "import", { "libraryName": "antd", "libraryDirectory": "lib", "style": true },  "antd" ],nodeExternals({

    whitelist: [/antd\/.*?\/style.*?/,/\.(css|less|sass|scss)$/],
  }),
