### ISSUE TITLE
按需加载不生效

### ISSUE THREAD

**Issue by killerlei** [ant-design/babel-plugin-import#304]
我用的create-react-app生成的项目，执行eject，然后增加.babelr文件，配置如下
<img width="338" alt="c4e59af9-2692-4192-9936-577273037988" src="https://user-images.githubusercontent.com/20664555/51460357-28e66b00-1d96-11e9-8bbb-b2c244d37824.png">

代码里面使用  import { Button} from antd
没有引用css文件
没有出现其他issues里面提到的css无效，一切正常，但是开发者工具仍然有warning
![9231-ac7](https://user-images.githubusercontent.com/20664555/51460565-c477db80-1d96-11e9-87a0-a04bb4ffc40a.png)

所以，按需加载是否真的生效，如果生效，为啥还会出现warning

**Comment by xyy94813** [comment]
@killerlei confirms whether `import { xxx } from ‘antd/lib/index’` exists in the project;

**Comment by killerlei** [comment]
> @killerlei confirms whether `import { xxx } from ‘antd/lib/index’` exists in the project;

确实遗留import {Layout} from "antd/lib/index";  改完以后warning消失了，打包体积小了0.4M了，多谢
