### ISSUE TITLE
文档中 import 语法的疑惑

### ISSUE THREAD

**Issue by cn-src** [ant-design/babel-plugin-import#314]
按官方文档所述 `import { Button } from 'antd';` 的写法引入了 antd 下所有的模块”。
需要使用 `import Button from 'antd/lib/button';` 或 babel-plugin-import 插件。

但我在使用 ant-design-vue 时，发现 `{Button} from 'ant-design-vue'` 和 `import Button from 'ant-design-vue/es/button'` 的写法，对生成文件的大小并没有什么影响。

**Comment by yukinotech** [comment]
别想了，我和你一样的问题。这个库根本没人维护，文档写的乱七八糟。你要是用的组件不多自己把需要的从源码里抠出来吧。

**Comment by afc163** [comment]
现代开发工具（如 vue-cli）基本都具备 [tree shaking](https://webpack.docschina.org/guides/tree-shaking/) 功能，能起到类似 babel-plugin-import 的效果。
