### ISSUE TITLE
if we want to suport multiple dependencies must beUpgrade to Babel 7?

### ISSUE THREAD

**Issue by dazjean** [ant-design/babel-plugin-import#317]
.babelrc 
```
{
    "presets":["es2015","react","stage-1"],
    "plugins": [
      ["transform-runtime"],
      ["import", {"libraryName": "antd","libraryDirectory": "lib","style": true},"antd"],
      ["import", {"libraryName": "cheui-react","libraryDirectory": "lib/components","camel2DashComponentName":true},"cheui-react"]
    ]
  }

```
only one import will be work. 
so...  we want to suport multiple dependencies must beUpgrade to Babel 7?

**Comment by aashishnagpal** [comment]
Hello.

Is anybody looking into the issues?

I am also facing this specific issue.

**Babel Version: 6.26.3**
**Babel Loader Version: 7.1.5**
**Babel Plugin Import Version: 1.11.2**

I tried using both named plugins and options array. In both cases _only_ the first options object is taken care of. All subsequent options/named plugins are simply ignored. 

Please tell if Babel Core 7+ is a must now or if there is a proper work around to support multiple dependencies?
Thanks

**Comment by dazjean** [comment]
> Hello.
> 
> Is anybody looking into the issues?
> 
> I am also facing this specific issue.
> 
> **Babel Version: 6.26.3**
> **Babel Loader Version: 7.1.5**
> **Babel Plugin Import Version: 1.11.2**
> 
> I tried using both named plugins and options array. In both cases _only_ the first options object is taken care of. All subsequent options/named plugins are simply ignored.
> 
> Please tell if Babel Core 7+ is a must now or if there is a proper work around to support multiple dependencies?
> Thanks

These codes are my solution .it can work in my project
```js
module.exports = {
    "presets":["es2015","react","stage-1"],
    "compact": false,
    "plugins": [
      ["transform-runtime"],
      ["import", [
        {
          "libraryName": "antd",
          "libraryDirectory": "lib",
          "style": true
        },
        {
          "libraryName": "cheui-react",
          "libraryDirectory": "lib/components",
          "camel2DashComponentName":true,
          "customName": (name) => {
            if (name === 'cheui'){
              return 'cheui-react/lib/index';
            }
            if(name === 'slider-group'){
              return `cheui-react/lib/components/slider/SliderGroup`;
            }
            if(name === 'group-image'){
              return `cheui-react/lib/components/image/Group`;
            }
            return `cheui-react/lib/components/${name}`;
          }
        }
        ]
      ]
      ]
  }


```
