### ISSUE TITLE
nuxt如何设置babel-plugin-import

### ISSUE THREAD

**Issue by ckaock** [ant-design/babel-plugin-import#347]
nuxt使用ui组件ant-design-vue，其他包都使用的最新版，尝试设置less-loader 和css-loader，都无法加载css或者报错。尝试了一天，无果。

**Comment by iiDestiny** [comment]
@sorrycc 遇到同样的问题，有好多人说解决了，其实他们只是引入了所有的压缩 css。

**Comment by gaga-change** [comment]
遇到同样的问题，研究了一下午，无果。

**Comment by afc163** [comment]
不需要用 babel-plugin-import 了，antd 和 webpack 现在都能支持 tree shaking。

**Comment by gp0320** [comment]
我最近也在用nuxt, 按需加载我试了搞定了，你们试下我的方法，
花了我一天一夜的工夫，看了源码。
https://juejin.im/post/5e012778518825127f085da8

**Comment by lvreninfo** [comment]
build: {
    transpile: ['ant-design-vue'],
    babel: {
      plugins: [
        ['import', {
          libraryName: 'ant-design-vue',
          libraryDirectory: 'es',
          style: 'css'
        }, 'ant-design-vue']
      ]
    }
}

**Comment by agrozyme** [comment]
我拿一個只有單個 page 的專案來比較，就結論來說，其總大小為
- 有按須加載: 3.75MB
- 無按須加載: 4.17MB
沒用按須加載的大了 11% 左右，但從絕對大小來看，我個人不覺得有太大差異～

這個案子沒有自訂 components
用到的 components 有
```
{
    'a-page-header': PageHeader,
    'a-button': Button,
    'a-popover': Popover,
    'a-icon': Icon,
    'a-tag': Tag,
    'a-modal': Modal,
    'a-spin': Spin,
    'a-alert': Alert,
    'a-tabs': Tabs,
    'a-tab-pane': Tabs.TabPane,
    'a-list': List,
    'a-list-item': List.Item,
    'a-list-item-meta': List.Item.Meta,
    'a-divider': Divider,
    'a-form-model': FormModel,
    'a-form-model-item': FormModel.Item,
    'a-cascader': Cascader,
    'a-input': Input,
    'a-radio': Radio,
    'a-radio-group': Radio.Group
}
```

**Comment by xiaofuliang** [comment]
请问题解决了吗？求解决方案

**Comment by gp0320** [comment]
> 请问题解决了吗？求解决方案

  build: {
   // 添加这个是关键，添加后babel才会处理依赖包vant里面的代码
    transpile: [ /vant.*?less/ ], 
   
    babel: {
      plugins: [
        ['import', {
          libraryName: 'vant',
          "style": (name) => {
            return `${name}/style/less.js`
          }
        }, 'vant']
      ],
    },
  }

**Comment by cluyun** [comment]
> 我最近也在用nuxt, 按需加载我试了搞定了，你们试下我的方法，
> 花了我一天一夜的工夫，看了源码。
> https://juejin.im/post/5e012778518825127f085da8

这又不是ant-design
