### ISSUE TITLE
How to create my own UI library that supports babel-plugin-import

### ISSUE THREAD

**Issue by youngzhaosignifyd** [ant-design/babel-plugin-import#361]
I am creating my own UI library. What do I need to do to support babel-plugin-import if someone installs my UI library through `npm install`? 

I was able to transpile all the js files using babel, but what do I need to do to transpile css/less/scss files into `style` folder? Do I need to write a custom script to do that? I searched the ant-design project but couldn't find any useful information.

**Comment by shaodahong** [comment]
`style` file path default is ``${module}/lib/${component}/style`` when `style` option set `true`

**Comment by youngzhaosignifyd** [comment]
@shaodahong Thanks!

**Comment by gomorizsolt** [comment]
@youngzhao-xyz Hey there! 👋 

Did you manage to find out how to output `style` folder including both the js and asset files? If so, would you mind sharing it how you accomplished it? I'm currently struggling with it and can't seem to get around it.

**Comment by gomorizsolt** [comment]
@youngzhao-xyz Feel free to disregard my comment above, it appears that I've just figured it out. :)
