### ISSUE TITLE
按需加载的组件库，内部引用的组件库没有按需加载

### ISSUE THREAD

**Issue by shenck215** [ant-design/babel-plugin-import#369]
前提：组件库A和B都可以分别用这个插件实现按需加载
场景：组件库A内部引用了组件库B，按需加载组件库A
结果：组件库A实现了按需加载，但其内部引用的组件库B没有实现
疑问：在这种场景下，想A和B都实现按需加载要怎么配置？

**Comment by shaodahong** [comment]
提供下 webpack 和 babel 的 config, 像是 exclude 了

**Comment by chj-damon** [comment]
我也遇到了类似的问题，在umi的项目里面用的。所以没有改webpack，我的babel.config.js长这样：
```js
module.exports = {
  presets: ['@babel/preset-typescript'],
  plugins: [
    [
      'import',
      {
        libraryName: '自定义组件库名',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ],
};
```

**Comment by shaodahong** [comment]
umi 我没用过不知道，试试 umi 的这个 https://umijs.org/zh/config/#extrababelincludes

**Comment by chj-damon** [comment]
没用。我换成create-react-app创建的项目里面这么用也是会样式丢失

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/1d4f240276447276045760f11e85e82db10004e8/components/dropdown/style/index.tsx#L4

**Comment by shaodahong** [comment]
> 没用。我换成create-react-app创建的项目里面这么用也是会样式丢失

如果可以, 尽量提供个复现的仓库我可以帮忙看看, 也能解决不少其他人遇到同样问题, 可能是 bug 也可能是用法的问题

**Comment by chj-damon** [comment]
> > 没用。我换成create-react-app创建的项目里面这么用也是会样式丢失
> 
> 如果可以, 尽量提供个复现的仓库我可以帮忙看看, 也能解决不少其他人遇到同样问题, 可能是 bug 也可能是用法的问题

按照偏右大佬给的办法解决了，他说不算是babel-plugin-import的bug。
PS：我觉得babel-plugin-import的功能有点瘸...

**Comment by afc163** [comment]
到今天 babel-plugin-import 的意义确实已经不大了，尤其是全量加载 css 其实也没多大：https://github.com/ant-design/ant-design/issues/16600#issuecomment-492572520

**Comment by shaodahong** [comment]
嗯,  之前的 tree-shaking 不是很成熟, 现在 sideEffects 其实能够缩减大部分的代码, 在生产环境使用是没问题的

**Comment by zpr1g** [comment]
> https://github.com/ant-design/ant-design/blob/1d4f240276447276045760f11e85e82db10004e8/components/dropdown/style/index.tsx#L4

哇偶，学习了，**style dependencies**
