### ISSUE TITLE
建议增加 styleLibraryDirectory 选项

### ISSUE THREAD

**Issue by StephenPCG** [ant-design/babel-plugin-import#381]
场景描述：

我使用 babel-plugin-import 来导入 element-ui，配置如下：
```js
['import', {
  libraryName: 'element-ui',
  style: (name) => {
    // name => 'element-ui/lib/button'
    // output => 'element-ui/lib/theme-chalk/button.css'
    return name.substring(0, 15) + 'theme-chalk/' + name.substring(15) + '.css'
  },
}, 'element-ui'],
```

该配置可以正常使用。然而，我希望结合 thread-loader 使用，但是 thread-loader 用 `JSON.stringify` 将 babel-loader 的 options 序列化然后传递给子进程，见 webpack-contrib/thread-loader#75 ，此处 `style` 为函数时无法传递，导致无法工作。

我知道该问题如果可以在 thread-loader 中解决是最好的，但是由于其进程模型，可能短时间内难以很好的解决，因此考虑在 babel-plugin-import 中增加一个 `styleLibraryDirectory`，如果配置中提供了 
```js
styleLibraryDirectory: 'theme-chalk',
```
那么使用该选项来构造 css 文件路径，否则仍然使用 `style` 选项，与现有行为兼容。

**Comment by afc163** [comment]
来个 pr 吧。
