### ISSUE TITLE
组件库文件命名必须是必须是 xx 或者 xx-xxx

### ISSUE THREAD

**Issue by qianjin1017** [ant-design/babel-plugin-import#426]
组件库文件XxXxx(DtButton)，配置按需加载报错，Module not found: Can't resolve 'dt-react-ant/es/dt-button' ， 实际上是找dt-button文件，这个应该怎么解决？

**Comment by qianjin1017** [comment]
通过修改组件库的文件名为 dt-button，可以解决以上问题。  但是这文件名驼峰报错很不合理的，忘修复！！！

**Comment by onaug6th** [comment]
我也遇到这个问题，请问是否有相关的配置能解决此问题呢

**Comment by onaug6th** [comment]
camel2DashComponentName 这个配置能完成你的要求
