### ISSUE TITLE
babel-plugin-import 动态引用less文件 和 mini-css-extract-plugin 导致引用顺序产生冲突

### ISSUE THREAD

**Issue by DemonCloud** [ant-design/babel-plugin-import#434]
![31585723721_ pic_hd](https://user-images.githubusercontent.com/7436361/78109790-81020e00-742c-11ea-8d18-ff4079783878.jpg)

先说结果:   
a.js
import { button, select } from 'antd-mobile'
b.js
import { select, button } from 'antd-mobile'

解析包之后会动态引入less
a.js
import button from 'antd-mobile/xxx/button'
import 'button.less'
import select from 'antd-mobile/xxx/select'
import 'select.less'

b.js
import select from 'antd-mobile/xxx/select'
import 'select.less'
import button from 'antd-mobile/xxx/button'
import 'button.less'

由于你两个文件在同一个chunk里的引入less的顺序不同, 在webpack构建时mini-css-extract-plugin会警告的顺序冲突.

请问有没有解决方法?

**Comment by DemonCloud** [comment]
当然webpack官方有说过,  css的引入是有顺序关系的. 
如果集成到js文件中来引入的时候, 变相会导致开发时也需要注意这个顺序

1. 要么一个个修改引用顺序, 或者直接引入一个总的less 不使用这个插件
2. 要么忽略警告
3.(or有没有更好的方法)

**Comment by afc163** [comment]
建议不使用这个插件，现在 tree shaking 基本能满足需求了，引入一个总的 less 文件也没多大。

**Comment by DemonCloud** [comment]
@afc163 恩, 理解
