### ISSUE TITLE
关于自定义样式文件名称customStyleName返回undefined或者空字符串的问题

### ISSUE THREAD

**Issue by BUPTlhuanyu** [ant-design/babel-plugin-import#435]
你好，近期有一个需求，某些import的组件不需要加样式，想在customStyleName中返回undefined或者空字符串通知plugin不要添加import节点。但是翻了一下源码，并没有在addSideEffect之前对`${stylePath}`进行非空判断。所以也算是一个有必要修复的bug吧。
`importMethod(methodName, file, pluginState) {
    if (!pluginState.selectedMethods[methodName]) {
      const libraryDirectory = this.libraryDirectory;  // 放置组件的文件夹路径
      const style = this.style; // 指定是否导入样式文件：boolean，string，function
      // 根据导入的模块的名称重新生成特定格式名称：camel2UnderlineComponentName为true表示在驼峰处用下划线链接，camel2DashComponentName为true表示在驼峰处用‘-’链接，否则不改变
      const transformedMethodName = this.camel2UnderlineComponentName  // eslint-disable-line
        ? transCamel(methodName, '_')
        : this.camel2DashComponentName
          ? transCamel(methodName, '-')
          : methodName;
      // 构建需要import的路径：比如import {Button} from 'antd' --> import Button from 'antd/lib/button'
      const path = winPath(
        this.customName ? this.customName(transformedMethodName) : join(this.libraryName, libraryDirectory, transformedMethodName, this.fileName) // eslint-disable-line
      );
      // transformToDefaultImport默认值为true，表示按默认导入的方式处理， 比如import Button from 'antd/lib/button'。 
      // 这里调用的就是addDefault为path添加默认导入的节点，导入后组件的名称为methodName
      pluginState.selectedMethods[methodName] = this.transformToDefaultImport  // eslint-disable-line
        ? addDefault(file.path, path, { nameHint: methodName })  // addDefault返回的是一个Identifier类型的节点，在后续如果有用到button那么，那么就会用这个Identifier节点来替换原来的Identifier
        : addNamed(file.path, methodName, path);
      // customStyleName与customName类似，生成样式文件的路径，以及节点
      if (this.customStyleName) {
        const stylePath = winPath(this.customStyleName(transformedMethodName));
        addSideEffect(file.path, `${stylePath}`);
      } else if (this.styleLibraryDirectory) {
        // 如果没有customStyleName，则加上styleLibraryDirectory指定的样式文件夹路径
        const stylePath = winPath(
          join(this.libraryName, this.styleLibraryDirectory, transformedMethodName, this.fileName)
        );
        addSideEffect(file.path, `${stylePath}`);
      } else if (style === true) {
        // 从style中找样式文件
        addSideEffect(file.path, `${path}/style`);
      } else if (style === 'css') {
        // 从style/css中找样式文件
        addSideEffect(file.path, `${path}/style/css`);
      } else if (typeof style === 'function') {
        // 如果是一个函数，则将传入组件的路径得到一个样式文件的路径
        const stylePath = style(path, file);
        if (stylePath) {
          addSideEffect(file.path, stylePath);
        }
      }
    }
    return Object.assign({}, pluginState.selectedMethods[methodName]);
  }`

**Comment by BUPTlhuanyu** [comment]
```
importMethod(methodName, file, pluginState) {
    if (!pluginState.selectedMethods[methodName]) {
      const libraryDirectory = this.libraryDirectory;  // 放置组件的文件夹路径
      const style = this.style; // 指定是否导入样式文件：boolean，string，function
      // 根据导入的模块的名称重新生成特定格式名称：camel2UnderlineComponentName为true表示在驼峰处用下划线链接，camel2DashComponentName为true表示在驼峰处用‘-’链接，否则不改变
      const transformedMethodName = this.camel2UnderlineComponentName  // eslint-disable-line
        ? transCamel(methodName, '_')
        : this.camel2DashComponentName
          ? transCamel(methodName, '-')
          : methodName;
      // 构建需要import的路径：比如import {Button} from 'antd' --> import Button from 'antd/lib/button'
      const path = winPath(
        this.customName ? this.customName(transformedMethodName) : join(this.libraryName, libraryDirectory, transformedMethodName, this.fileName) // eslint-disable-line
      );
      // transformToDefaultImport默认值为true，表示按默认导入的方式处理， 比如import Button from 'antd/lib/button'。 
      // 这里调用的就是addDefault为path添加默认导入的节点，导入后组件的名称为methodName
      pluginState.selectedMethods[methodName] = this.transformToDefaultImport  // eslint-disable-line
        ? addDefault(file.path, path, { nameHint: methodName })  // addDefault返回的是一个Identifier类型的节点，在后续如果有用到button那么，那么就会用这个Identifier节点来替换原来的Identifier
        : addNamed(file.path, methodName, path);
      // customStyleName与customName类似，生成样式文件的路径，以及节点
      if (this.customStyleName) {
        const stylePath = winPath(this.customStyleName(transformedMethodName));
        addSideEffect(file.path, `${stylePath}`);
      } else if (this.styleLibraryDirectory) {
        // 如果没有customStyleName，则加上styleLibraryDirectory指定的样式文件夹路径
        const stylePath = winPath(
          join(this.libraryName, this.styleLibraryDirectory, transformedMethodName, this.fileName)
        );
        addSideEffect(file.path, `${stylePath}`);
      } else if (style === true) {
        // 从style中找样式文件
        addSideEffect(file.path, `${path}/style`);
      } else if (style === 'css') {
        // 从style/css中找样式文件
        addSideEffect(file.path, `${path}/style/css`);
      } else if (typeof style === 'function') {
        // 如果是一个函数，则将传入组件的路径得到一个样式文件的路径
        const stylePath = style(path, file);
        if (stylePath) {
          addSideEffect(file.path, stylePath);
        }
      }
    }
    return Object.assign({}, pluginState.selectedMethods[methodName]);
  }
```

**Comment by HongSiyuan** [comment]
最近也遇到了这个问题，请问你最终是怎么处理的呢
