### ISSUE TITLE
All styles of antd are injected except for progress widget's css

### ISSUE THREAD

**Issue by dgreene1** [ant-design/babel-plugin-import#467]
My `.babelrc`:
```json
{
    "plugins": [["import", {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": "css"
      }]]
}
```

After rollup is complete, here's what can be seen. 

> var css_248z$6 = "@-webkit-keyframes scaleDown{0%{transform:scale(1)}50%{transform:scale(.95)}to{transform:scale(1)}}@keyframes scaleDown{0%{transform:scale(1)}50%{transform:scale(.95)}to{transform:scale(1)}}@-webkit-keyframes scaleUp{0%{transform:scale(1)}50%{transform:scale(1.1)}to{transform:scale(1)}}@keyframes scaleUp{0%{transform:scale(1)}50%{transform:scale(1.1)}to{transform:scale(1)}}@-webkit-keyframes fadeIn{0%{opacity:0}to{opacity:1}}@keyframes fadeIn{0%{opacity:0}to{opacity:1}}@-webkit-keyframes fadeOut{0%{opacity:1}to{opacity:0}}@keyframes fadeOut{0%{opacity:1}to{opacity:0}}@-webkit-keyframes slideInDown{0%{opacity:0;transform:translateY(-100px)}75%{transform:translateY(0)}to{opacity:1}}@keyframes slideInDown{0%{opacity:0;transform:translateY(-100px)}75%{transform:translateY(0)}to{opacity:1}}@-webkit-keyframes slideInUp{0%{opacity:0;transform:translateY(100px)}75%{transform:translateY(0)}to{opacity:1}}@keyframes slideInUp{0%{opacity:0;transform:translateY(100px)}75%{transform:translateY(0)}to{opacity:1}}@-webkit-keyframes slideInRight{0%{opacity:0;transform:translateX(100px)}75%{transform:translateX(0)}to{opacity:1}}@keyframes slideInRight{0%{opacity:0;transform:translateX(100px)}75%{transform:translateX(0)}to{opacity:1}}@-webkit-keyframes slideInLeft{0%{opacity:0;transform:translateX(-100px)}75%{transform:translateX(0)}to{opacity:1}}@keyframes slideInLeft{0%{opacity:0;transform:translateX(-100px)}75%{transform:translateX(0)}to{opacity:1}}.ant-progress-bg,.ant-progress-success-bg{background-color:#0064d6}.ant-progress-text{color:#484848}.ant-progress-inner{background-color:#d9d9d9}.ant-progress-status-success .anticon svg{display:none}.ant-progress-status-success .ant-progress-bg{background-color:#76c463}.ant-progress-status-success .ant-progress-text:before{content:\"100%\";color:#484848}.ant-progress-status-exception .anticon svg{display:none}.ant-progress-status-exception .ant-progress-bg{background-color:#e74c3c}.ant-progress-status-exception .ant-progress-text:before{content:\"Failed\";color:#484848}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIlZ0eFByb2dyZXNzLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBNENBLDZCQUNFLEdBQ0Usa0JBQXFCLENBQ3ZCLElBQ0Usb0JBQXdCLENBQzFCLEdBQ0Usa0JBQXFCLENBQUUsQ0FOM0IscUJBQ0UsR0FDRSxrQkFBcUIsQ0FDdkIsSUFDRSxvQkFBd0IsQ0FDMUIsR0FDRSxrQkFBcUIsQ0FBRSxDQUUzQiwyQkFDRSxHQUNFLGtCQUFxQixDQUN2QixJQUNFLG9CQUF1QixDQUN6QixHQUNFLGtCQUFxQixDQUFFLENBTjNCLG1CQUNFLEdBQ0Usa0JBQXFCLENBQ3ZCLElBQ0Usb0JBQXVCLENBQ3pCLEdBQ0Usa0JBQXFCLENBQUUsQ0FFM0IsMEJBQ0UsR0FDRSxTQUFZLENBQ2QsR0FDRSxTQUFZLENBQUUsQ0FKbEIsa0JBQ0UsR0FDRSxTQUFZLENBQ2QsR0FDRSxTQUFZLENBQUUsQ0FFbEIsMkJBQ0UsR0FDRSxTQUFZLENBQ2QsR0FDRSxTQUFZLENBQUUsQ0FKbEIsbUJBQ0UsR0FDRSxTQUFZLENBQ2QsR0FDRSxTQUFZLENBQUUsQ0FFbEIsK0JBQ0UsR0FDRSxTQUFVLENBQ1YsNEJBQStCLENBQ2pDLElBQ0UsdUJBQTBCLENBQzVCLEdBQ0UsU0FBWSxDQUFFLENBUGxCLHVCQUNFLEdBQ0UsU0FBVSxDQUNWLDRCQUErQixDQUNqQyxJQUNFLHVCQUEwQixDQUM1QixHQUNFLFNBQVksQ0FBRSxDQUVsQiw2QkFDRSxHQUNFLFNBQVUsQ0FDViwyQkFBOEIsQ0FDaEMsSUFDRSx1QkFBMEIsQ0FDNUIsR0FDRSxTQUFZLENBQUUsQ0FQbEIscUJBQ0UsR0FDRSxTQUFVLENBQ1YsMkJBQThCLENBQ2hDLElBQ0UsdUJBQTBCLENBQzVCLEdBQ0UsU0FBWSxDQUFFLENBRWxCLGdDQUNFLEdBQ0UsU0FBVSxDQUNWLDJCQUE4QixDQUNoQyxJQUNFLHVCQUEwQixDQUM1QixHQUNFLFNBQVksQ0FBRSxDQVBsQix3QkFDRSxHQUNFLFNBQVUsQ0FDViwyQkFBOEIsQ0FDaEMsSUFDRSx1QkFBMEIsQ0FDNUIsR0FDRSxTQUFZLENBQUUsQ0FFbEIsK0JBQ0UsR0FDRSxTQUFVLENBQ1YsNEJBQStCLENBQ2pDLElBQ0UsdUJBQTBCLENBQzVCLEdBQ0UsU0FBWSxDQUFFLENBUGxCLHVCQUNFLEdBQ0UsU0FBVSxDQUNWLDRCQUErQixDQUNqQyxJQUNFLHVCQUEwQixDQUM1QixHQUNFLFNBQVksQ0FBRSxDQUVsQiwwQ0FFRSx3QkFBMkIsQ0FFN0IsbUJBQ0UsYUFBZ0IsQ0FFbEIsb0JBQ0Usd0JBQTJCLENBRTdCLDBDQUNFLFlBQWUsQ0FFakIsOENBQ0Usd0JBQTJCLENBRTdCLHVEQUNFLGNBQWUsQ0FDZixhQUFnQixDQUVsQiw0Q0FDRSxZQUFlLENBRWpCLGdEQUNFLHdCQUEyQixDQUU3Qix5REFDRSxnQkFBaUIsQ0FDakIsYUFBZ0IiLCJmaWxlIjoiVnR4UHJvZ3Jlc3Muc2NzcyIsInNvdXJjZXNDb250ZW50IjpbIi8qXG4gKiBmdW5jdGlvbnMgZm9yIHBhcnNpbmcgdmFyaWFibGUgdmFsdWVzIGZyb20gU0NTUyBNYXBzXG4gKlxuICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqL1xuLypcbiAqIGZvbnQgZGVjbGFyYXRpb25zXG4gKlxuICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cbi8qXG4gICogZGVmaW5lZCBjb2xvciBtYXBcbiAgKlxuICAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovXG4vKlxuICAqIGNvbG9yIGFzc2lnbm1lbnRzXG4gICpcbiAgKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cbi8qXG4gKiBtaXhpbnNcbiAqXG4gKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovXG4vKlxuICogZGVmaW5lIEJFTSBuYW1pbmcgY29udmVudGlvbnNcbiAqXG4gKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqL1xuLypcbiAqIHJldGluYSBiYWNrZ3JvdW5kIGltYWdlXG4gKlxuICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cbi8qXG4gKiB0eXBvZ3JhcGh5XG4gKlxuICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cbi8qXG4gKiB2ZXJ0aWNhbCBhbGlnbm1lbnQgb2YgY29udGVudCBpbiBjb250YWluZXJcbiAqXG4gKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqL1xuLypcbiAqIGN1c3RvbSBib290c3RyYXAgbWl4aW4gZm9yIGNvbXBhY3QgZ3JpZCBjb2x1bW5zXG4gKlxuICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKi9cbi8qXG4gKiB0cmFuc2l0aW9uc1xuICpcbiAqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKiovXG5Aa2V5ZnJhbWVzIHNjYWxlRG93biB7XG4gIDAlIHtcbiAgICB0cmFuc2Zvcm06IHNjYWxlKDEpOyB9XG4gIDUwJSB7XG4gICAgdHJhbnNmb3JtOiBzY2FsZSgwLjk1KTsgfVxuICAxMDAlIHtcbiAgICB0cmFuc2Zvcm06IHNjYWxlKDEpOyB9IH1cblxuQGtleWZyYW1lcyBzY2FsZVVwIHtcbiAgMCUge1xuICAgIHRyYW5zZm9ybTogc2NhbGUoMSk7IH1cbiAgNTAlIHtcbiAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMSk7IH1cbiAgMTAwJSB7XG4gICAgdHJhbnNmb3JtOiBzY2FsZSgxKTsgfSB9XG5cbkBrZXlmcmFtZXMgZmFkZUluIHtcbiAgMCUge1xuICAgIG9wYWNpdHk6IDA7IH1cbiAgdG8ge1xuICAgIG9wYWNpdHk6IDE7IH0gfVxuXG5Aa2V5ZnJhbWVzIGZhZGVPdXQge1xuICAwJSB7XG4gICAgb3BhY2l0eTogMTsgfVxuICB0byB7XG4gICAgb3BhY2l0eTogMDsgfSB9XG5cbkBrZXlmcmFtZXMgc2xpZGVJbkRvd24ge1xuICAwJSB7XG4gICAgb3BhY2l0eTogMDtcbiAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTEwMHB4KTsgfVxuICA3NSUge1xuICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgwKTsgfVxuICAxMDAlIHtcbiAgICBvcGFjaXR5OiAxOyB9IH1cblxuQGtleWZyYW1lcyBzbGlkZUluVXAge1xuICAwJSB7XG4gICAgb3BhY2l0eTogMDtcbiAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMTAwcHgpOyB9XG4gIDc1JSB7XG4gICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApOyB9XG4gIDEwMCUge1xuICAgIG9wYWNpdHk6IDE7IH0gfVxuXG5Aa2V5ZnJhbWVzIHNsaWRlSW5SaWdodCB7XG4gIDAlIHtcbiAgICBvcGFjaXR5OiAwO1xuICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWCgxMDBweCk7IH1cbiAgNzUlIHtcbiAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoMCk7IH1cbiAgMTAwJSB7XG4gICAgb3BhY2l0eTogMTsgfSB9XG5cbkBrZXlmcmFtZXMgc2xpZGVJbkxlZnQge1xuICAwJSB7XG4gICAgb3BhY2l0eTogMDtcbiAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTEwMHB4KTsgfVxuICA3NSUge1xuICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWCgwKTsgfVxuICAxMDAlIHtcbiAgICBvcGFjaXR5OiAxOyB9IH1cblxuLmFudC1wcm9ncmVzcy1zdWNjZXNzLWJnLFxuLmFudC1wcm9ncmVzcy1iZyB7XG4gIGJhY2tncm91bmQtY29sb3I6ICMwMDY0ZDY7IH1cblxuLmFudC1wcm9ncmVzcy10ZXh0IHtcbiAgY29sb3I6ICM0ODQ4NDg7IH1cblxuLmFudC1wcm9ncmVzcy1pbm5lciB7XG4gIGJhY2tncm91bmQtY29sb3I6ICNkOWQ5ZDk7IH1cblxuLmFudC1wcm9ncmVzcy1zdGF0dXMtc3VjY2VzcyAuYW50aWNvbiBzdmcge1xuICBkaXNwbGF5OiBub25lOyB9XG5cbi5hbnQtcHJvZ3Jlc3Mtc3RhdHVzLXN1Y2Nlc3MgLmFudC1wcm9ncmVzcy1iZyB7XG4gIGJhY2tncm91bmQtY29sb3I6ICM3NmM0NjM7IH1cblxuLmFudC1wcm9ncmVzcy1zdGF0dXMtc3VjY2VzcyAuYW50LXByb2dyZXNzLXRleHQ6OmJlZm9yZSB7XG4gIGNvbnRlbnQ6ICcxMDAlJztcbiAgY29sb3I6ICM0ODQ4NDg7IH1cblxuLmFudC1wcm9ncmVzcy1zdGF0dXMtZXhjZXB0aW9uIC5hbnRpY29uIHN2ZyB7XG4gIGRpc3BsYXk6IG5vbmU7IH1cblxuLmFudC1wcm9ncmVzcy1zdGF0dXMtZXhjZXB0aW9uIC5hbnQtcHJvZ3Jlc3MtYmcge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZTc0YzNjOyB9XG5cbi5hbnQtcHJvZ3Jlc3Mtc3RhdHVzLWV4Y2VwdGlvbiAuYW50LXByb2dyZXNzLXRleHQ6OmJlZm9yZSB7XG4gIGNvbnRlbnQ6ICdGYWlsZWQnO1xuICBjb2xvcjogIzQ4NDg0ODsgfVxuIl19 */";
styleInject(css_248z$6);

Notice that there is no css for `.ant-progress`. Yes, you'll see `.ant-progress-success` and some of the other classes, but without the styles for the standard widget, the progress widget does not look correct.

**Comment by yhy-vertex** [comment]
This is also an issue in skeleton widget where it does not inject.

**Comment by dgreene1** [comment]
FYI, we believe that the issue @yhy-vertex and I were experiencing might have been caused by importing the components like this:
```ts
import Pagination, { PaginationConfig } from 'antd/lib/pagination';
```

But it doesn't work if you import from the `antd/lib` directory. So do this instead:
```ts
import { Pagination } from 'antd';
import { PaginationConfig } from 'antd/lib/pagination';
```

Closing this since this seems to fix the issue.
