### ISSUE TITLE
1.13.2 版本bug

### ISSUE THREAD

**Issue by yangxuanxing** [ant-design/babel-plugin-import#554]
所有用了这个包的构建都失败了：

![image](https://user-images.githubusercontent.com/3397523/100052129-41bf7c00-2e58-11eb-928e-259a337bf3dd.png)

**Comment by ycjcl868** [comment]
重新安装下依赖，dist-tag 已经指回去了

**Comment by xiezhuo0513** [comment]
现在还是打包失败的情况啊

**Comment by mochen666** [comment]
现在还是打包失败的情况啊 +1

**Comment by TangBX** [comment]
现在还是打包失败的情况啊 +2

**Comment by TangZhenPeng24** [comment]
![Uploading image.png…]()

**Comment by TangZhenPeng24** [comment]
现在还是打包失败的情况啊 +3

**Comment by since181220** [comment]
现在还是打包失败的情况啊 +5

**Comment by ycjcl868** [comment]
依赖 update 下（或者删除 node_modules、yarn.lock、package-lock.json 重新执行下安装）

**Comment by Slebee** [comment]
删除 node_modules、yarn.lock、package-lock.json 重新执行下安装
还是一样没区别啊

**Comment by wmy1992** [comment]
still not work after update

**Comment by thinkive** [comment]
都2022,4月份了，仍然有问题，是问题又重现了？还是一直没解决？

**Comment by zhouzhoudi** [comment]
懂不懂babel作者的含金量啊？

**Comment by AieraFlyyyy** [comment]
same question

**Comment by haojing924** [comment]
出现了同样的问题，主要前两天构建的时候这个问题并没有出现

**Comment by soonlive** [comment]
同样的问题，升级到 1.13.3 版本解决了，npm i -D babel-plugin-import@1.13.3

**Comment by jwqStoneatom** [comment]
> 同样的问题，升级到 1.13.3 版本解决了，npm i -D babel-plugin-import@1.13.3

铁子, 没有解决....
