### ISSUE TITLE
1.13.2版本出错

### ISSUE THREAD

**Issue by hongrunhui** [ant-design/babel-plugin-import#559]
![image](https://user-images.githubusercontent.com/9162319/100066834-80613080-2e70-11eb-9a6b-75c1e0315dc4.png)
![image](https://user-images.githubusercontent.com/9162319/100066939-9bcc3b80-2e70-11eb-962c-23a33dbf967a.png)
1.13.1就没事
发布包的时候好好检查一下行不

**Comment by mwb-27** [comment]
哈哈哈，我刚提单3分钟，看到又有一个提单的

**Comment by shilongfeicool** [comment]
/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault' 被这个路径困扰了半天

**Comment by zhouyinchi** [comment]
求助，依赖antd,里面安装了最新的这个版本，怎么指定低版本

**Comment by hongrunhui** [comment]
楼上我建议你定个外卖再来解决这个问题
把package.json里的版本号前面的^去掉

**Comment by zhouyinchi** [comment]
"/.umi-production/umi.ts: Cannot find module '/Users/chencheng/Code/..."，项目依赖umi，umi依赖babel-plugin-import，然后umi是在服务器环境安装的，里面的版本号改不了呢

**Comment by sorrycc** [comment]
Fixed via 1.13.3 .
