### ISSUE TITLE
style 设置为 true 后未加载组件样式

### ISSUE THREAD

**Issue by ITJesse** [ant-design/babel-plugin-import#58]
https://github.com/ant-design/ant-design/issues/900#issue-127675746

And that will convert this

```
import { Button } from 'antd';
ReactDOM.render(<Button>xxxx</Button>, mountNode);
```

to

```
var _button = require('antd/lib/button');
require('antd/style/components/button');
ReactDOM.render(<Button>xxxx</Button>, mountNode);
```

但是实际上样式并没有被成功加载

**Comment by hufeng** [comment]
同样的问题
```js
//.babelrc
{
  "presets": ["react", "es2015"],
  "plugins": [
    "syntax-object-rest-spread",
    ["antd", { "style": "css", "libraryName": "antd-mobile" }]
  ]
}

//package.json
{
  "dependencies": {
    "antd-mobile": "^0.7.8",
    "react": "^15.3.1",
    "react-dom": "^15.3.1",
    "rmc-list-view": "^0.6.1"
  },
  "devDependencies": {
    "babel-loader": "^6.2.5",
    "babel-plugin-antd": "^0.5.1",
    "babel-plugin-syntax-object-rest-spread": "^6.13.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "css-loader": "^0.24.0",
    "html-webpack-plugin": "^2.22.0",
    "style-loader": "^0.13.1",
    "webpack": "^2.1.0-beta.21",
    "webpack-dev-server": "^1.15.0"
  }
}

```

**Comment by motorguo** [comment]
@ #61 

` 也许可以到你`

**Comment by mydearxym** [comment]
我遇到了同样的问题，暂时的解决办法：

1.  因为 antd 默认引入的是 [less](https://github.com/ant-design/ant-design/blob/master/components/button/style/index.tsx#L1)，所以你先装一个 webpack  的 [less-loader](https://github.com/webpack/less-loader) 
2. 然后你引入组件的时候使用这种繁琐的写法：

```js
import Tag from 'antd/lib/tag';
require('antd/lib/tag/style');
```

实际上你按照插件文档设置 css options 是没有用的，我之前在 #47 就被坑过。 这当然是 bug。

**Comment by Honghe** [comment]
@mydearxym 能否给出详细配置，我的 less-loader 编译 less 出错，好像没生效
```
demo_ethereum/node_modules/antd/lib/style/index.less:1
(function (exports, require, module, __filename, __dirname) { @import "./themes/default";
                                                              ^
SyntaxError: Unexpected token ILLEGAL
```

**Comment by zation** [comment]
这里面还有可能是你的 css loader 设置了 css module。。。我就是因为这个样式加载不了，解决方法：
```js
{
      test: /\.less$/,
      loader: `style!css?${cssLoaderWithoutModule}!postcss!less?${lessLoader}`,
      include: [
        path.resolve(__dirname, 'node_modules'),
      ],
    }
```

**Comment by crowphy** [comment]
如果我需要使用css modules功能怎么办？

**Comment by cike8899** [comment]
cssLoaderWithoutModule   lessLoader 这两个变量是什么值？

**Comment by zhangxianggui** [comment]
我的解决方案

**Comment by viix** [comment]
使用less-loader有效
```
{
        test: /\.less$/,
        loader: `style!css!less`,
        include: path.resolve(__dirname, 'node_modules'),
}
```

**Comment by JustYJQ** [comment]
@viix  
include: path.resolve(__dirname, 'node_modules'),
ReferenceError: path is not defined

**Comment by JustYJQ** [comment]
@zhangxianggui  
还是不行啊

**Comment by viix** [comment]
@JustYJQ 
```var path = require('path')```

**Comment by mytharcher** [comment]
https://segmentfault.com/q/1010000007626617

这个题主采纳的答案解决了。

**Comment by geekpeng** [comment]
@Honghe 我也遇到这个问题 请问你怎么解决的

**Comment by fred104** [comment]
@zhangxianggui You save my day!

**Comment by paranoidjk** [comment]
First, Please see api doc at https://github.com/ant-design/babel-plugin-import#style

I will try to give a simple explanation:

1. Since antd have below file structure https://unpkg.com/antd@2.10.2/lib/affix/style/

```bash
node_modules/antd/lib/button/style                                                                                               jiangkai@jiangkaideMacBook-Pro
├──  css.js
├──  index.css
├──  index.d.ts
├──  index.js
├──  index.less
└──  mixin.less
```
2. If you set `style: true`, babel-plugin-import will load style by `require('antd/lib/message/style')`, which means this file https://unpkg.com/antd@2.10.2/lib/button/style/index.js, as you can see, it's **css file**.

3. If you set `style:  'css'`, babel-plugin-import will load style by `require('antd/lib/button/style/css')`, which means https://unpkg.com/antd@2.10.2/lib/button/style/index.js, it's **less file**. 

4. Last tip, you need configure webpack loader(`css-loader/less-loader`) to handle `css/less` file by yourself.


Going to close this issue, If anyone still got problems, please provide a reproducible demo.

**Comment by Pines-Cheng** [comment]
无论是设置为css还是设置为true，样式都没能加载。

**Comment by OuFeng** [comment]
折腾了这么旧终于可用了。贴上解决方案：

// .babelrc or babel-loader option
"plugins": [["import", { "libraryName": "antd", "style": "css" }]]


//webpack.config.js设置
rules: [
            {
                test: /\.css$/,
                use: [
                    { loader: 'style-loader' },
                    { loader: 'css-loader', options: { modules: true, importLoaders: 1 } },
                    { loader: 'postcss-loader' }
                ],
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                use: [
                    { loader: 'style-loader' },
                    { loader: 'css-loader' }
                ],
                include: /node_modules/
            }
]

参考:
https://stackoverflow.com/questions/35398733/css-modules-how-do-i-disable-local-scope-for-a-file

**Comment by JX-Zhuang** [comment]
U can see
https://github.com/ant-design/ant-design/issues/3442#issuecomment-374877201

**Comment by zhangyang110** [comment]
我特么就服了，题主问的是style 设置为 true后样式消失的问题，你们让他吧true再改成css ，跟没说有啥区别。谁能说个答案呢！

**Comment by Vevlins** [comment]
{
        test: /\.css$/i,
        // include: /src/,
        use: [
          { loader: "style-loader" },
          { loader: "css-loader", options: { modules: true } },
          { loader: "postcss-loader", options: postcssOpts }
        ]
      }
---
 { test: /\.less$/i, loaders: ['style-loader', 'css-loader', 'less-loader'] },
---
  ["import", [{ style: true, libraryName: "antd-mobile" }]]
---
部门大佬写的，我这里遇到的问题是通过css modules来写样式之后，自己向组件内传样式不生效，不知道跟你们的相不相同

**Comment by ITJesse** [comment]
I think what @paranoidjk said is very clear. And I don't know why someone still have this problem in the year 2018. Due to this issue is posted in 2016, if you have the same problem maybe you should check your version again.

Remember, complaints cannot solve any problem.

I have no more problem with roadhog now, please give it a try.
```
{
  "entry": "./src/renderer/index.js",
  "outputPath": "./app/dist",
  "publicPath": "../dist/",
  "define": {
    "$dirname": "__dirname"
  },
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr",
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": true }]
      ]
    },
    "production": {
      "extraBabelPlugins": [
        "transform-runtime",
        ["import", { "libraryName": "antd", "style": true }]
      ]
    }
  },
  "theme": {
    "@icon-url": "\"~antd-iconfont/iconfont\"",
    "primary-color": "#2CCB27"
  }
}
```

**Comment by bin-soft** [comment]
可以问一下，你们配置的这个文件是在哪里的呢

**Comment by weidapao** [comment]
···
{
        test: /\.css$/,
        use: [
          {
            loader: "style-loader"
          },
          {
            loader: "css-loader",
            options: {
              // modules: true,  // antd必须去掉此项才有样式
              importLoaders: 1,
              localIdentName: "[name]_[local]_[hash:base64]",
              sourceMap: true,
              minimize: true
            }
          }
        ]
      }
···

**Comment by zsirfs** [comment]
@weidapao 有办法解决的。css module 和 antd有冲突，看umi和 roadhog的配置，已经解决了这个问题。自己配置的也有办法解决的

**Comment by weidapao** [comment]
@zsirfs 配置可以发我一份吗

**Comment by sjfkai** [comment]
This is my solution:
 
       npm i --save-dev react-app-rewire-less

change config-overrides.js:

```js
const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
  // do stuff with the webpack config...
  config = injectBabelPlugin(['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }], config);

  config = rewireLess.withLoaderOptions({
    javascriptEnabled: true,
  })(config, env)
  
  return config;
};
```

**Comment by afc163** [comment]
@wujohns 

https://github.com/ant-design/babel-plugin-import/blob/38841b6f34b69df5c16e5910fc20f78bb1d4d095/src/Plugin.js

**Comment by aflext** [comment]
已经放弃按需引用

**Comment by chengwangping** [comment]
@afc163 有没有什么办法既可以满足theme定制 又可以使用css modules?

**Comment by gouding** [comment]
设置为true不生效，若你是按照官网的步骤来操作，可能的原因是你使用css-loader或less-loader设置了className为module的方式进行处理，antd里不能使用带hash的class类型进行处理，不然不会生效。

```
....其他...
 {
      test: /\.less$/,
      exclude: /node_modules/,  //这个用于你自己的样式处理，所以去除掉node_modules里的项
      use: [{
        loader: "style-loader"
      }, {
        loader: "css-loader",
        options: {
          modules: true,   //采用className={styles.xxx}的方式进行添加样式
          localIdentName: '[local]--[hash:base64:5]'
        }
      }, {
        loader: "less-loader",
      }]
    },
    {
      test: /\.less$/,
      include: /node_modules/,  //这个是用于antd 必须要处理node_modules
      use: [{
        loader: "style-loader"
      }, {
        loader: "css-loader",
      }, {
        loader: "less-loader",
        options: {
          modifyVars: {   //这是自定义主题色等等...
            "primary-color": "#0DAEAF",
            "link-color": "#0DAEAF",
          },
          javascriptEnabled: true,
        }
      }]
    },
....其他...
```

**Comment by Ba5sx1a0sen1** [comment]
> 设置为true不生效，若你是按照官网的步骤来操作，可能的原因是你使用css-loader或less-loader设置了className为module的方式进行处理，antd里不能使用带hash的class类型进行处理，不然不会生效。
> 
> ```
> ....其他...
>  {
>       test: /\.less$/,
>       exclude: /node_modules/,  //这个用于你自己的样式处理，所以去除掉node_modules里的项
>       use: [{
>         loader: "style-loader"
>       }, {
>         loader: "css-loader",
>         options: {
>           modules: true,   //采用className={styles.xxx}的方式进行添加样式
>           localIdentName: '[local]--[hash:base64:5]'
>         }
>       }, {
>         loader: "less-loader",
>       }]
>     },
>     {
>       test: /\.less$/,
>       include: /node_modules/,  //这个是用于antd 必须要处理node_modules
>       use: [{
>         loader: "style-loader"
>       }, {
>         loader: "css-loader",
>       }, {
>         loader: "less-loader",
>         options: {
>           modifyVars: {   //这是自定义主题色等等...
>             "primary-color": "#0DAEAF",
>             "link-color": "#0DAEAF",
>           },
>           javascriptEnabled: true,
>         }
>       }]
>     },
> ....其他...
> ```

完美的解决了问题，这个方法是正确的

**Comment by zry754331875** [comment]
@Honghe你的问题解决了吗？我是用razzle做ssr的时候会报这个问题，跟你一模一样的错误

**Comment by wuhao5436** [comment]
说一下我的经验：
"create-react-app": "3.0.1",
"webpack": "4.29.6",
"antd-mobile": "^2.2.13",

**出现less引不到，或者引到不能用的问题，可能有两处错误**；
1. 首先是按需加载的less文件没有加载进来，解决方法就是安装babel-plugin-import，然后在babel-loader里按照官方提供的方法使用

```
{
              test: /\.(js|mjs|jsx|ts|tsx)$/,
              include: paths.appSrc,
              loader: require.resolve('babel-loader'),
              options: {
                customize: require.resolve(
                  'babel-preset-react-app/webpack-overrides'
                ),
                plugins: [
                  ["import", { libraryName: "antd-mobile", style: true }] // `style: true` 会加载 less 文件
                ]
              },
},
```



2. 文件加载进来以后经过less-loader配置的modules:true把类名hash化了

解决方法就是 @gouding 提供的方法
我这里使用的create-react-app -v 3.0.1, eject出来的webpack.config.js,中使用了oneOf关键字，我把lessRegex，lessModuleRegex设置成了统一的 /\.less$/；
```
 // ---add---
            {
              test: lessRegex,
              exclude: /node_modules/,
              use: getStyleLoaders(
                {
                  importLoaders: 2,
                  modules:true, // 除去/node_modules/中的文件，我们都需要hash化
                  sourceMap: isEnvProduction && shouldUseSourceMap,
                },
                'less-loader'
              ),
              sideEffects: true,
            },
            {
              test: lessModuleRegex,
              include: /node_modules/,
              use: getStyleLoaders(
                {
                  importLoaders: 2,
                  sourceMap: isEnvProduction && shouldUseSourceMap,
                  // modules: true,   // /node_modules/中的less文件，不需要hash化
                  getLocalIdent: getCSSModuleLocalIdent,
                },
                'less-loader'
              ),
            },
//----add---
```

**Comment by hzaMozilla** [comment]
.babelrc的配置：{"plugins": [["import", { "style": "css", "libraryName": "antd-mobile" }]]}
备注：style设置为"true"或者"css"都可以；libraryName可根据实际使用选"antd-mobile" or "antd"

然后在webpack.config.js下的module配置：
module: {
      rules: [
        {
          test: /\.css$/, 
          loader: 'style-loader!css-loader'
        }
      ]
}
备注：预先install 一下style-loader和css-loader

**Comment by IFmiss** [comment]
如果是用的less，且使用了 css modules 的话， 可以将  css 文件的 css modules 配置关闭
```code
// babel 配置
[
    'import',
    {
      libraryName: 'antd',
      libraryDirectory: 'lib',
      style: 'css'
    }
 ]


// webpack 配置
{
  test: /\.(c)ss$/,
  use: [
    devMode ? 'style-loader' : MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      // options: {
      //   modules:true
      // }
    },
    {
      loader:"postcss-loader",
      options: {
	plugins: () => [
		require('autoprefixer')()
	]
      }
    },
  ]
},

```
注释掉 css modules 配置就好了

**Comment by caoyuyu1213** [comment]
> {
>         test: /\.css$/,
>         use: [
>           {
>             loader: "style-loader"
>           },
>           {
>             loader: "css-loader",
>             options: {
>               // modules: true,  // antd必须去掉此项才有样式
>               importLoaders: 1,
>               localIdentName: "[name]_[local]_[hash:base64]",
>               sourceMap: true,
>               minimize: true
>             }
>           }
>         ]
>       }

强如老哥啊，想请教下这个原因是啥啊
