### ISSUE TITLE
webpack 5 + vue 3自定义脚手架配置 babel-plugin-import 没生效

### ISSUE THREAD

**Issue by heart-er** [ant-design/babel-plugin-import#589]
环境
webpack: 5.41.1
vue: 3.1.2
webpack-cli: 4.7.2
@babel/core: 7.14.7
babel-loader: 8.2.2
@babel/plugin-transform-runtime: 7.14.5
@babel/runtime-corejs3: 7.14.7

问题：
babel.config.js中添加配置后，样式文件并没有引入，查看控制面板中的css，发现css也没有被下载
配置如下:
![image](https://user-images.githubusercontent.com/24717511/129347832-170a0525-ab0e-439a-bb2d-2927d9a9fba8.png)

预期：
在导入对应组件的时候，可以正常引入css文件

Note：大概率不是我配置的问题，因为我在同样ts配置中使用了ts-import-plugin，可以生效，但是基于JS中的不行

**Comment by heart-er** [comment]
所以官方后面是不打算兼容 or 修复了么 看issue 该插件在webpack 5 中确实存在许多问题

**Comment by bpuns** [comment]
我也用webpack5试了，发现并没有生效

**Comment by heart-er** [comment]
不好意思 当时截图放错，后来使用了正确的方式也是不行，上面截图已更新

**Comment by heart-er** [comment]
另外 组件是可以正常引入的，只是样式没有生效

**Comment by perfectyang** [comment]
有demo代码吗，发链接我去调试一下
