### ISSUE TITLE
和transform-react-inline-elements插件冲突

### ISSUE THREAD

**Issue by wmzy** [ant-design/babel-plugin-import#64]
和 transform-react-inline-elements 同时用的时候会报异常，如：`ReferenceError: Alert is not defined`
猜测是和这个有关：

> Note that this requires the global polyfill due to React's use of ES6 Symbol when validating React Elements. If Symbol is not present in the browser, your application will fail to render, as Babel will polyfill Symbol but React will not have access to that polyfill. Therefore, you must require the global polyfill at the entry point to your application: require("babel-polyfill");

版本：
babel-plugin-antd@0.5.1
babel-plugin-transform-react-inline-elements@6.8.0

**Comment by paranoidjk** [comment]
从报错文案来看与 babel-plugin-import 无关， 请提供一个可复现的 demo。
