### ISSUE TITLE
libraryDirectory参数不支持空白字符串？

### ISSUE THREAD

**Issue by CrisLi** [ant-design/babel-plugin-import#66]
想将babel-plugin-antd插件和material-ui结合用。

将
```es6
import {RaisedButton} from 'material-ui';
```
转换成
```es6
import RaisedButton from 'material-ui/RaisedButton';
```

但设置参数时发现问题，如果如下设置，libraryDirectory会用默认值`lib`，有没有办法就是空白字符，这样就能支持material-ui了吧。
```json
"plugins": [["antd", { "libraryName": "material-ui", "libraryDirectory": "" }]]
```

**Comment by CrisLi** [comment]
看了一下babel-plugin-antd源码，上面的问题应该可以传参数`.`来解决，但总觉不太好。

此外还有一个问题是，[这行代码](https://github.com/ant-design/babel-plugin-antd/blob/master/src/Plugin.js#L18)强制调用了`camel2Dash`方法，对于material-ui也是不友好。可否加一个配置项来告诉插件是否需要转换`methodName`。

**Comment by afc163** [comment]
感觉可以做的更通用一点，并改名为 `babel-plugin-import`。@sorrycc

**Comment by sorrycc** [comment]
@afc163 好，节后我做下，感觉是通用需求了。

**Comment by sorrycc** [comment]
已支持。
