### ISSUE TITLE
typescript 环境下无法按需加载

### ISSUE THREAD

**Issue by ImJoeHs** [ant-design/babel-plugin-import#73]
atnd: 2.0.0
ts: 2.0.0
babel-plugin-import: 1.0.1
atool-build: 0.8.1

```
webpackConfig.babel.plugins.unshift(['import', {
    'libraryName': 'antd',
    'style': 'css',  // if true, use less
  }]);]
```

结果整个antd打包进去了

**Comment by afc163** [comment]
ts 编译走的不是 babel 吧？babel 插件自然没用。

**Comment by ImJoeHs** [comment]
```
        {
          test: /\.tsx?$/,
          loaders: ['babel', 'ts'],
        },
```
这样子的耶，这样会不走babel吗？

**Comment by afc163** [comment]
先 babel 再 ts ？

给个重现 repo 吧。

**Comment by ImJoeHs** [comment]
我使用了atool-build，上面那个loader也来自https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js，仅仅写了个入口，没有其他额外代码。刚看到这边有个一样的问题https://github.com/ant-tool/atool-build/issues/175。

**Comment by hellopao** [comment]
@ImJoeHs  你把tsconfig.json里的module的配置改成es2015就可以了。

**Comment by bccsafe** [comment]
@afc163 
重现 repo: https://github.com/bccsafe/typescript-react-redux-antd

antd: 2.5.3
babel-plugin-import: 1.1.0
typescript: 2.0.3
ts-loader: 0.9.0
babel: 6

先 babel 再 ts的，没有按需加载，css也没进去，麻烦看下

**Comment by AepKill** [comment]
我也是这个问题。

**Comment by xiaocaibird** [comment]
同样的问题，mark一下

**Comment by MrKou47** [comment]
同问，很急

**Comment by ImJoeHs** [comment]
太久了都忘了提过这个，当时忘了回来补充下close掉=-=
解决方案就像上面 @hellopao说的

> 把tsconfig.json里的module的配置改成es2015就可以了。

@MrKou47 先ts

**Comment by MrKou47** [comment]
```js
            {
                test: /\.tsx?$/,
                loader: 'ts-loader!babel-loader',
                exclude: /node_modules/,
            },
```
```json
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": [["import", {
      "libraryName": "antd",
      "style": true
  }]]
}
```
这样写一直报错...

**Comment by ImJoeHs** [comment]
@MrKou47 loader执行的顺序是right to left

**Comment by bccsafe** [comment]
忘记说了 我的问题是typescript用了"module": "commonjs"的配置

https://github.com/bccsafe/typescript-react-redux-antd 也更新好了

**Comment by IvanZheng** [comment]
@ImJoeHs  能分享下你的webpack.config.js吗, 如何得到webpackConfig.babel.plugins?
我也遇到一样的问题, 因为是先ts-loader , 这个时候所有的antd的包已经都转换成了es2015的js, 然后babel-loader已经没机会按需加载打包了. 

我的loader配置如下, "webpack": "^2.2.1" ,  "babel-loader": "^6.2.5",  "babel-plugin-import": "^1.1.0"
 module: {
        loaders: [
          {
              test: /\.ts(x?)$/,
              exclude: "./node_modules",
              //babel在ts之后load, 所以babel-plugin-import 无效
              loader: 'babel-loader?presets[]=es2015!ts-loader'
              //loader: 'babel-loader?'+JSON.stringify({"presets":["es2015"],plugins:[["import",{"libraryName":"antd","style": true }]]}) + '!ts-loader'
          },

**Comment by IvanZheng** [comment]
@sorrycc 是否有可能提供一个ts-plugin-import 用于ts-loader?

**Comment by IvanZheng** [comment]
去掉 tsconfig中的"module": 要设成es6或者es2015才行.  如果不设置module,那么target是es6也可以. 问题解决了. 这样的话ts-loader就不会直接编译成commonjs, 而是es6了.

**Comment by ImJoeHs** [comment]
我感觉我还是再发一次吧。。方便后面的同学看

babel-plugin-import只支持es6 module写法的代码
tsconfig中必须指定module为ES
而module的default值

> target === "ES6" ? "ES6" : "CommonJS"
所以就像楼上说的那样。

再说三遍 tsconfig module tsconfig module tsconfig module

**Comment by gwuhaolin** [comment]
[ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 可以非常方便的做到。

它是一个 babel-plugin-import 的代替品，一个 Webpack Loader，优势有：
- 性能更好；
- 能用于非 Babel 的项目，只要你的项目使用 Webpack 构建即可；

**Comment by linmodev** [comment]
@gwuhaolin 如果我没用webpack怎么按需加载？
