### ISSUE TITLE
it would be nice to add support for more libs

### ISSUE THREAD

**Issue by plandem** [ant-design/babel-plugin-import#74]
e.g.:  lodash (babel-plugin-lodash), react-intl (babel-plugin-react-intl)

**Comment by ericclemmons** [comment]
I just attempted to use this with `lodash`:

```json
{
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-0"
  ],
  "plugins": [
    ["import", [
      { "libraryName": "lodash", "libraryDirectory": "" }
    ]]
  ]
}
```

The problem is you get errors like:
> Module not found: Error: Can't resolve 'lodash/map-values'

It's not in the README, but you can pass off `false` to other arguments in the constructor:
> https://github.com/ant-design/babel-plugin-import/blob/2e206e5c9c9fd7c7fd9a4a1589d533a9a6856da8/src/Plugin.js#L4

- `camel2DashComponentName: false`
- `camel2UnderlineComponentName: false`

**Comment by paranoidjk** [comment]
https://github.com/ant-design/babel-plugin-import#options
