### ISSUE TITLE
在引入 less 的情况下，如何使用自己的 theme？

### ISSUE THREAD

**Issue by zation** [ant-design/babel-plugin-import#76]
如果我希望用自己的 theme 来覆盖 ant 自带的，那我是不是就不能用 `style: true` 这个配置了，而必须手动引入所有的 less 文件，并且引入自己的 theme.less ？

**Comment by sorrycc** [comment]
`style: true` 就是走的 less 文件吧。

**Comment by zation** [comment]
@sorrycc 对，但是我需要覆盖 ant 自带的 `themes/default.less` 的 variables...

**Comment by pfdgithub** [comment]
变量可以覆盖，但是ant定义的变量还是不够多，很多样式还是需要全局覆盖。
#78

**Comment by afc163** [comment]
参考：https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme
