### ISSUE TITLE
无法按需加载,能帮我看看是什么问题嘛

### ISSUE THREAD

**Issue by wq199151** [ant-design/babel-plugin-import#77]
只能以这种方式引入
//import 'antd-mobile/lib/toast/style/index.css';
//import Toast from 'antd-mobile/lib/toast';

这种方式就报错了
//import {Toast} from 'antd-mobile';

============================我的webpack配置文件
module.exports = {
    entry: {
        app: './src/js/index.js',
        vendors: [
            'react',
            'react-dom',
        ]
    },
    output: {
        path: path.join(__dirname, 'build'),
        //publicPath: '/Hybrid.Example/build/',
        filename: "js/[name].js",
        chunkFilename: "js/[id].chunk.js",
        sourceMapFilename: 'js/[name].map',
        hash: true
    },
    resolve: {
        modulesDirectories: ['node_modules', path.join(__dirname, '../node_modules')],
        extensions: ['', '.web.js', '.js', '.json'],
    },
    module: {
        loaders: [
            {
                test: /.js?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['react', 'stage-2', 'es2015']
                },
                "plugins": [["import", {
                    "libraryName": "antd-mobile",
                    "libraryDirectory": "lib",
                    "style": "css"
                }]]
            },
            {
                test: /.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader")
            },
            {
                test: /.(gif|jpg|png|woff|svg|eot|ttf)\??.*$/,
                loader: 'url?limit=204800'
            }

```
    ]
},
plugins: [
    new webpack.ProvidePlugin({}),
    new webpack.optimize.CommonsChunkPlugin('vendors', 'js/vendors.js'),
    new ExtractTextPlugin("css/[name].css"),
    new HtmlWebpackPlugin({                        //根据模板插入css/js等生成最终HTML
        //favicon:'./src/img/favicon.ico', //favicon路径
        filename: 'index.html',    //生成的html存放路径，相对于 path
        template: './src/index.html',    //html模板路径
        inject: true,    //允许插件修改哪些内容，包括head与body
        hash: true,    //为静态资源生成hash值
        minify: {    //压缩HTML文件
            removeComments: true,    //移除HTML中的注释
            collapseWhitespace: false    //删除空白符与换行符
        }
    }),
    new webpack.DefinePlugin({
        'process.env': {
            NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        }
    })
]
```

};

**Comment by sorrycc** [comment]
报什么错? (p.s. 格式麻烦调整下，看起来累)

**Comment by wq199151** [comment]
entry: {
        app: './src/js/index.js',
        vendors: [
            'react',
            'react-dom'
        ]
    },
    output: {
        path: path.join(__dirname, 'build'),
        //publicPath: '/Hybrid.Example/build/',
        filename: "js/[name].js",
        chunkFilename: "js/[id].chunk.js",
        sourceMapFilename: 'js/[name].map',
        hash: true
    },
    resolve: {
        modulesDirectories: ['node_modules', path.join(__dirname, '../node_modules')],
        extensions: ['', '.web.js', '.js', '.json']
    },
    module: {
        loaders: [
            {
                test: /\.js?$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                query: {
                    presets: ['react', 'stage-2', 'es2015']
                },
                "plugins": [["import", {
                    "libraryName": "antd-mobile",
                    "libraryDirectory": "lib",
                    "style": "css"
                }]]
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader")
            },
            {
                test: /\.(gif|jpg|png|woff|svg|eot|ttf)\??.*$/,
                loader: 'url?limit=204800'
            }

        ]
    },
    plugins: [
        new webpack.ProvidePlugin({}),
        new webpack.optimize.CommonsChunkPlugin('vendors', 'js/vendors.js'),
        new ExtractTextPlugin("css/[name].css"),
        new HtmlWebpackPlugin({                        //根据模板插入css/js等生成最终HTML
            //favicon:'./src/img/favicon.ico', //favicon路径
            filename: 'index.html',    //生成的html存放路径，相对于 path
            template: './src/index.html',    //html模板路径
            inject: true,    //允许插件修改哪些内容，包括head与body
            hash: true,    //为静态资源生成hash值
            minify: {    //压缩HTML文件
                removeComments: true,    //移除HTML中的注释
                collapseWhitespace: false    //删除空白符与换行符
            }
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(process.env.NODE_ENV),
            }
        })
    ]
#######################################################
> 编译的时候报
ERROR in ./src/js/index.js
Module not found: Error: Cannot resolve module 'antd-mobile' in /Users/wangqian/Project/CBD_Project/HelloWorld/src/js
resolve module antd-mobile in /Users/wangqian/Project/CBD_Project/HelloWorld/src/js
  looking for modules in /Users/wangqian/Project/CBD_Project/node_modules
    resolve 'file' antd-mobile in /Users/wangqian/Project/CBD_Project/node_modules
      resolve file
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile is not a file
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile.web.js doesn't exist
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile.js doesn't exist
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile.json doesn't exist
    resolve 'file' or 'directory' /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile
      resolve file
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile is not a file
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile.web.js doesn't exist
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile.js doesn't exist
        /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile.json doesn't exist
      resolve directory
        directory default file index
          resolve file index in /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile
            /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile/index doesn't exist
            /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile/index.web.js doesn't exist
            /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile/index.js doesn't exist
            /Users/wangqian/Project/CBD_Project/node_modules/antd-mobile/index.json doesn't exist


少了lib这一层

**Comment by wq199151** [comment]
我只能指定文件这种方式
//import 'antd-mobile/lib/toast/style/index.css';
//import Toast from 'antd-mobile/lib/toast';  

用这个就跪了- - 
import {Toast} from 'antd-mobile';

**Comment by pfdgithub** [comment]
可以在loader中指定plugins吗？我在.babelrc文件中配置没问题。
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    [
      "import",
      {
        "style": true,
        "libraryName": "antd-mobile"
      }
    ]
  ]
}

**Comment by Robot-L** [comment]
你位置错了，把plugins放到query里面就可以了（文档里描述的也太不清楚了- - ||）
```js
   query: {
          presets: ['react','es2015'],
          plugins: [["import", {"libraryName": "antd","style": "css"} ]]
        },
```

**Comment by paranoidjk** [comment]
If you use webpack 2, configuration see https://github.com/babel/babel-loader#options
