### ISSUE TITLE
字体本地加载

### ISSUE THREAD

**Issue by qiaolb** [ant-design/babel-plugin-import#78]
能否增加一个参数，设置@icon-url，指定本地加载字体，这样既可以本地加载字体，也可以按需加载样式。

**Comment by pfdgithub** [comment]
我在less-loader中对ant-design路径下的less文件，使用modifyVars覆盖icon-url变量到本地。
`{
  // 覆盖 antd-mobile 变量
  test: function (absPath) {
    return (/\.less$/).test(absPath)
      && absPath.includes(path.join('antd-mobile', 'lib'));
  },
  loader: `style-loader!css-loader!postcss-loader!less-loader?${JSON.stringify({
    modifyVars: {
      'icon-url': '\'~styles/anticon/iconfont\''
    }
  })}`)
}`

**Comment by FTAndy** [comment]
假如在不影响全局污染的情况下，直接加 query 也是可以的，但是要注意单双引号，不然很容易悲剧
```javascript
const iconPath = path.join(__dirname, 'yourpath/icon/iconfont')

{
  test: /\.less$/,
  loader: `style!css!less?{"modifyVars": {"icon-url": "'${iconPath}'"}}`,
}
```

**Comment by paranoidjk** [comment]
我的看法，字体文件没必要做分组件按需加载，antd 是一份单独的字体文件。

如果我对这个需求理解不正确，请留言或 reopen。

**Comment by paranoidjk** [comment]
sorry， 我理解错了。

不是按需加载字体，是按需加载样式的同时使用本地字体。

**Comment by paranoidjk** [comment]
请使用 theme 来定制主题。 https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont
