### ISSUE TITLE
允许使用者自定义转换规则

### ISSUE THREAD

**Issue by pfdgithub** [ant-design/babel-plugin-import#80]
最好能暴露出转换规则，这样可以支持更多类库。
找到一个插件，可以实现通用类库导入，但是不支持追加样式。
[babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports)
这个完全支持自定义导入
[babel-plugin-imports](https://www.npmjs.com/package/babel-plugin-imports)

**Comment by afc163** [comment]
支持正则或者函数就好了。

**Comment by pfdgithub** [comment]
webpack 2 开始支持 Tree shaking 特性，在此之前还是需要基于文件的导入方式，这个插件还是有需要的。

**Comment by paranoidjk** [comment]
trace at https://github.com/ant-design/babel-plugin-import/issues/105
