### ISSUE TITLE
loader加载器里配置不起作用

### ISSUE THREAD

**Issue by zmGitHub** [ant-design/babel-plugin-import#83]
使用babel-plugin-import的时候把配置写在babel-loader 里面不起作用, 在.babelrc里面是可以的  但是打包完了以后还是提示:
![image](https://cloud.githubusercontent.com/assets/6838405/19504850/45371aaa-95f0-11e6-8b49-4d08e04d6445.png)
如下是我的配置文件:
![image](https://cloud.githubusercontent.com/assets/6838405/19504864/5a44a7be-95f0-11e6-8e63-c3f4c9255baf.png)
.babelrc的配置:
![image](https://cloud.githubusercontent.com/assets/6838405/19504873/6f0650e4-95f0-11e6-8794-fb1d439e84ba.png)
这个问题貌我测试了好多遍了 还是这样, 请指教

**Comment by roybein** [comment]
看bundle出来的文件大小，应该已经按需加载了，可能这个warning误报了

**Comment by afc163** [comment]
看看是否这个问题：https://github.com/ant-design/babel-plugin-import/issues/81#issuecomment-254698003

**Comment by paranoidjk** [comment]
Close for no response, if you still have problem, feel free to reopen.
