### ISSUE TITLE
symlinked antd: Module not found: 'style' 

### ISSUE THREAD

**Issue by timoxley** [ant-design/babel-plugin-import#84]
Using webpack, I can't seem to get the `import { Input } from 'antd'` syntax to work if the `antd` installation is a symlink in `node_modules`. 

If the `antd` installation is moved into `node_modules/antd` without the symlink, everything works entirely as expected.

```
Error in ../antd/lib/button/style/css.js
Module not found: 'style' in /a/b/c/…/antd/lib/button/style
```
- babel-plugin-import 1.0.1
- webpack 1.13.2
- antd 2.1.0
- node v6.7.0

**Comment by paranoidjk** [comment]
Even if antd is installed by symlink, as you can see , this file reauire path will still work, https://unpkg.com/antd@2.10.2/lib/button/style/index.js.

Please give a reproducible demo if you still got problem.

More detail info please see  https://github.com/ant-design/ant-design-mobile/wiki/How-babel-plugin-import-load-stysheet%3F
