### ISSUE TITLE
Component loads but without style

### ISSUE THREAD

**Issue by whphhg** [ant-design/babel-plugin-import#89]
I'm using electron with electron-compile instead of webpack. I've prepared a minimal reproducible example of the problem, located [here](https://github.com/whphhg/antd-example-problem).

1. In the example .compilerc "style" is set to "less" which loads the component but without any style.

2. If you change "style" to true it throws the following error:
`../node_modules/antd/lib/style/index.less:1 Uncaught SyntaxError: Invalid or unexpected token`

3. If you change the "style" to "css" it throws the following error:
`../node_modules/antd/lib/style/index.css:10 Uncaught SyntaxError: Unexpected token {`

Is webpack absolutely necessary to load styles on demand and use a custom theme or can the provided example be adjusted to work with electron-compile?

Thank you for taking the time to respond in advance.

**Comment by zywcode** [comment]
The same problem.
How to resolve.

**Comment by afc163** [comment]
You need https://github.com/webpack/css-loader/ and https://github.com/webpack/less-loader

**Comment by apremalal** [comment]
Tried with the following configuration, it doesn't work.

```
// webpack.config.js
module.exports = {
    ...
    module: {
        rules: [{
            test: /\.less$/,
            use: [{
                loader: "style-loader" // creates style nodes from JS strings
            }, {
                loader: "css-loader" // translates CSS into CommonJS
            }, {
                loader: "less-loader" // compiles Less to CSS
            }]
        }]
    }
};
```

**Comment by CoaPsyFactor** [comment]
any updates on this?

I'm also facing same issue.

**Comment by alexnsouza6** [comment]
Facing this problem either. Please, if someone knows how to fix it, tell us!

**Comment by alexnsouza6** [comment]
Hello, everyone, I solved this issue importing the respective css files.

In my case, I was using Input, Select, Cascader components of Antd for a **REACT Project** and the styles wasn't loading. So I figured out the paths of each css files and imported them all like below:

import 'antd/es/input/style/index.css';
import 'antd/es/select/style/index.css';
import 'antd/es/cascader/style/index.css';

This isn't the most beautiful and engineering way to do this, but it works.
Hope help u all

**Comment by jbwhitcombe** [comment]
Just in case someone recent stumbles upon this after missing something as well, you need to add:
`@import '~antd/dist/antd.css';`
To the top of either/both of App.css and Index.css.

Hope that helps! 👍

**Comment by SourceCipher** [comment]
Its not working at all if you try to style the components using **less**. I imported into my `main.less` like
`@import '~antd/dist/antd.less';` and then imported the `main.less` inside my jsx. The page loads but there are no styles of the antd at all

**Comment by babarali581** [comment]
I had a same issue but I solved . Created a file webpackrc in root directory and paste following script 
{
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
  ]
}

**Comment by eduFDiaz** [comment]
I solved the problem including this link in my index.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/antd/3.11.6/antd.css"></link>

**Comment by ckreiling** [comment]
Just had the same problem. Same solution as @babarali581, but `libraryDirectory` set to `"lib"` and `style` set to `true`.

```json
{
  "extraBabelPlugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": true }]]
}
```

`package.json` dependencies:

```json
 {
    "antd": "^3.13.4",
    "babel-plugin-import": "^1.11.0",
    "customize-cra": "^0.2.11",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "react": "^16.8.2",
    "react-app-rewired": "^2.1.0",
    "react-dom": "^16.8.2",
    "react-scripts": "2.1.5"
  }
```

Using `create-react-app` with the `customize-cra` anti-ejector.

**Comment by miteshpant** [comment]
> Just in case someone recent stumbles upon this after missing something as well, you need to add:
> 
> `@import '~antd/dist/antd.css';`
> 
> To the top of either/both of App.css and Index.css.
> 
> Hope that helps! 👍

Thanks a lot

**Comment by samialmorshedi** [comment]
I`m using Rails and Webpacker. How can I fix the problem importing Antd  style?

**Comment by jbcazaux** [comment]
> In my case, I was using Input, Select, Cascader components of Antd for a **REACT Project** and the styles wasn't loading. So I figured out the paths of each css files and imported them all like below:
> 
> import 'antd/es/input/style/index.css';
> import 'antd/es/select/style/index.css';
> import 'antd/es/cascader/style/index.css';
> 
You don t need to specify index.css : )
When I m using a component i just write : 
import { DatePicker } from 'antd'
import 'antd/es/date-picker/style'

**Comment by rustyonrampage** [comment]
In your index.js file, you can import ant style files: 
import 'antd/dist/antd.css';

Reference: https://ant.design/docs/react/getting-started

**Comment by tayrotayro** [comment]
> Just in case someone recent stumbles upon this after missing something as well, you need to add:
> 
> `@import '~antd/dist/antd.css';`
> 
> To the top of either/both of App.css and Index.css.
> 
> Hope that helps! 👍

This is the way to go for all of those who are struggling. Thank you ghost

**Comment by pantuts** [comment]
thanks @ghost

**Comment by WildSaoFeng** [comment]
> I solved the problem including the style in my index.html https://cdnjs.cloudflare.com/ajax/libs/antd/3.11.6/antd.css

Also solved by using your solution! Couldn't say enough thank to you!

**Comment by DanielBok** [comment]
For those who like to use less files in antd, so that they can modify the theme variables, try out the following configuration below.

Redacted to contain the main parts

```tsx
// index.ts 

import "antd/dist/antd.less";  // using less file here instead of .css so that we can modify variables
ReactDOM.render(<App />, document.getElementById("root"));

// another file
import styles from "./styles.less";  // custom component less, uses CSS modules
import { Button } from "antd";

const Component = () => (
  <div className={styles.myStyle}>
    <div>The color shouldn't be blue if you modified the @primary-color variable in the config</div>
    <Button type="primary">My Button</Button>
  </div>;
```

### Using webpack

```javascript
// webpack.config.js
{
    test: /\.less$/,
    use: [
      {
        loader: MiniCssExtractPlugin.loader,
        options: { hmr: !isProduction },
      },
      {
        loader: "css-loader",
        options: {
          modules: {
            // if you define your styles in the "styles.less" file as ".my-style", when you import into your component
            // you use it like "className={styles.myStyle}"  (camel-cased)"
            exportLocalsConvention: "camelCase",
   
            // for your webpack to re-write the generated css file eventually
            localIdentName: isProduction ? "[hash:base64]" : "[path][name]_[local]",

            // most important step to use antd less and your own less files, if you use css-loader, by default it'll "fudge"
            // the styles when you import any less files with hashes and whatever, using this, you can customize it
            getLocalIdent: (context, localIdentName, localName, options) => {
              const { resourcePath } = context;

              // if files come from node_modules, like when you `import "antd/dist/antd.less", you don't want your css-loader
              // to fudge the name. Meaning you want your ".antd-button" from the less file to remain ".antd-button" instead of
              // ".antd-button__[hash]" like ".antd-button__13be5". Otherwise, it'd look as though your antd components aren't
              // styled
              if (resourcePath.includes("node_modules")) {
                return localName;
              }

              // for your own styles and components, you want to hash it because chances are, using css-modules, you likely used
              // the same name, like ".my-styles" across many files and components. `resourcePath` is the absolute path of the
              // stylesheet (i.e. /path/to/my/component/styles.less) and `localName` is the name of the style `my-style`. 
              // md5 => `const md5 = require("md5");` and 
              // btoa => `const { encode: btoa } = require("js-base64");`  base64
              // this hash is guaranteed to be locally unique and almost globally unique
              // substring optional but I think 6 characters usually fine
              const hash = btoa(md5(`${resourcePath}.${localName}`)).substring(0, 6);

              // create your own custom classname. So your style will eventually be [filename]_[styleName]__[hash]
              // i.e. (styles_background__abcde). If you used `<div className={styles.background} />`, it'll be transpiled to
              // `<div className="styles_background__abcde" />`
              return `${path.parse(resourcePath).name}_${localName}__${hash}`;
            },
          },
        },
      },
      {
        loader: "less-loader", // compiles Less to CSS
        options: {
          javascriptEnabled: true,
          modifyVars: {
            // this allows you to modify the all less variables. antd has a set of variables that you can see from
            // https://ant.design/docs/react/customize-theme#Ant-Design-Less-variables
            // however, you can also overwrite your own like @my-height so that all my-height in all less files are overwritten
            "@primary-color": "#292929",
          },
        },
      },
    ],
  },
```

If you use CRA, you can use craco and craco-antd as such

```craco.config.js
const getCSSModuleLocalIdent = require("react-dev-utils/getCSSModuleLocalIdent");

module.exports = {
  plugins: [
    {
      plugin: CracoAntDesignPlugin,
      options: {
        cssLoaderOptions: {
          modules: {
            localIdentName: isProduction ? "[hash:base64]" : "[path][name]_[local]",
            getLocalIdent: (context, localIdentName, localName, options) =>
              context.resourcePath.includes("node_modules")
                ? localName
                : getCSSModuleLocalIdent(context, localIdentName, localName, options),
          },
          localsConvention: "camelCase",
        },
      },
    },
  ],
};
```

**Comment by S-Rahemi** [comment]
If you have added some classes to app.css with HTML elements reference like **div{...}** or **input{...}**, it can make conflict
