### ISSUE TITLE
文档中的用法写错了

### ISSUE THREAD

**Issue by shengliangli** [ant-design/babel-plugin-import#92]
["import", [{ "libraryName": "antd" }]]: import js modularly
["import", [{ "libraryName": "antd", "style": true }]]: import js and css modularly (less source files)
["import", [{ "libraryName": "antd", "style": "css" }]]: import js and css modularly (css built files)

应该是：
[["import", { "libraryName": "antd" }]]: import js modularly
[["import", { "libraryName": "antd", "style": true }]]: import js and css modularly (less source files)
[["import", { "libraryName": "antd", "style": "css" }]]: import js and css modularly (css built files)

**Comment by ShadowRambler** [comment]
大家来找茬？

**Comment by newset** [comment]
居然还没有更正。这个略坑

**Comment by Ireland999** [comment]
具体怎么使用

**Comment by Ireland999** [comment]
babel如何打包antd的所引用的css文件，webpack.config.js文件中如何去配置？
