### ISSUE TITLE
无法自动引入CSS样式

### ISSUE THREAD

**Issue by lockon23012** [ant-design/babel-plugin-import#95]
import { DatePicker } from 'antd';
按说明进行了配置，还是无法自动引入CSS样式

![image](https://cloud.githubusercontent.com/assets/6327668/20737710/727682ca-b6e9-11e6-985f-5923e1fc5396.png)

**Comment by beiduo** [comment]
1. 安装```npm install babel-plugin-import --save-dev```
2. 在.babelrc中加入 
    ```
    "plugins": [
        ["import", {
          "libraryName": "antd",
          "libraryDirectory": "lib",
          "style": "css"
        }]
    ]
    ```
3. 安装```npm install style-loader --save-dev``` 和 ```npm install css-loader --save-dev```
4. 在webpack config中添加
    ```
    {
        test: /\.css$/, // Only .css files
        loader: 'style!css'
    }
    ```
    **不要exclude node_modules目录**

**Comment by terryc129** [comment]
@beiduo 请问如果config 里有`exclude: /node_modules/` plugin是不能用的么？但是一般情况下都会有这个exclude的设置不能改的。有什么解决办法么？

**Comment by MrKou47** [comment]
还是不行啊，我也是这样

**Comment by sym900728** [comment]
不能使用。

**Comment by beiduo** [comment]
@terryc129 

exclude了之后就不行吧
如果实在不行，可以改用less

.babelrc

```
      ["import", {
        "libraryName": "antd",
        "libraryDirectory": "lib",
        "style": true
      }]
```

webpack使用less-loader

下面是webpack2的配置

```
      {
        test: /\.less$/,
        use: [ 'style-loader', 'css-loader', 'less-loader' ]
      },
```

**Comment by terryc129** [comment]
@beiduo 
谢谢，我还是没有用 babel-plugin-import，直接从 `antd/lib/` import component和css。好处是可以直接在css上customize.

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/How-babel-plugin-import-load-stysheet%3F
