### ISSUE TITLE
Cannot find module 'less'

### ISSUE THREAD

**Issue by JustYJQ** [ant-design/babel-plugin-import#98]
ERROR in Cannot find module 'less'
 @ ./~/antd/lib/style/index.less 4:14-102 13:2-17:4 14:20-108

ERROR in Cannot find module 'less'
 @ ./~/antd/lib/button/style/index.less 4:14-108 13:2-17:4 14:20-114

**Comment by infeng** [comment]
`npm install less`

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design-mobile/wiki/How-babel-plugin-import-load-stysheet%3F
